# Turns what extract.js took out of the running MeshOptimiser app into the design band's parts:
#   apps/meshoptimiser/ui.css        the app's own CSS rules for them
#   apps/meshoptimiser/ui-parts.json  their markup, with the wrappers they need (#sidebar-right ...)
#   apps/meshoptimiser/ui/            the Fasteners clip and poster
#
# Retake:
#   1. Open the app at 1728 x 1117 on a model that is free to show, Clay view. Run Smart optimise,
#      set Exploded view to 40 %, run Fasteners (then close and reopen the card), open the library drawer.
#   2. Run tools/ui-capture/extract.js in that page (it needs window.__s from the screenshot helpers only for
#      nothing: it reads the DOM). Save what it returns as extract.json.
#   3. python tools/ui-capture/build.py extract.json <app folder>/assets/help
#   4. node tools/build-app-site.js, and bump the ?v= of ui.css / ui-parts.json in site.js.
import json, os, re, shutil, sys

here = os.path.dirname(os.path.abspath(__file__))
site = os.path.join(here, '..', '..', 'apps', 'meshoptimiser')
d = json.load(open(sys.argv[1], encoding='utf8'))
app_help = sys.argv[2]

# ---- css: the app's own rules, with :root turned into :host ----
vars_css = [v.replace(':root', ':host', 1) for v in d['vars'] if v.split('{')[0].strip().startswith(':root')]
rules = [r for r in d['rules'] if not re.match(r'^\s*(html|body)\b', r.split('{')[0])]
css = '/* Rules copied from the running app (index.html) for the parts shown in the design band.\n   Generated by tools/ui-capture/build.py; do not edit by hand. */\n'
css += ':host { display: block; font: 400 13px/1.4 Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #ededed; -webkit-font-smoothing: antialiased; text-align: left; letter-spacing: normal; }\n'
css += '\n'.join(vars_css) + '\n' + '\n'.join(rules) + '\n'
css += """
/* ---- how the parts sit in the stage (not from the app) ---- */
#sidebar-right { width: 256px; }
#sidebar-left { width: 248px; }
#vp-overlay { position: relative; display: block; width: auto; height: auto; }
#vp-overlay .vpc { position: static; }
#viewport { display: block; position: relative; }
#vp-library-pop { position: relative !important; inset: auto !important; transform: none !important; width: 620px; height: auto !important; border-radius: 10px; overflow: hidden; }
#vp-library-pop .lib-dock-body { display: block; }
#vp-library-pop #lib-list { max-height: 188px; overflow: hidden; }
.section-cmd { position: relative !important; inset: auto !important; transform: none !important; width: 300px; max-height: none !important; }
#tb { width: 760px; position: relative; overflow: hidden; border-radius: 10px; }
.cmd-hero video { display: block; width: 100%; height: auto; }
.doc-tab-name, .doc-tab-name .dtn-a { max-width: none !important; overflow: visible !important; text-overflow: clip !important; }
.doc-tab { width: auto !important; min-width: 0; }
.doc-tabs { width: auto; max-width: none; }
.doc-tab-name .dtn-b { display: none !important; }
"""
open(os.path.join(site, 'ui.css'), 'w', encoding='utf8').write(css)

# ---- markup: each part with the ancestors its selectors expect ----
wrap = {
    'smart': ('<div id="sidebar-right">', '</div>'), 'explode': ('<div id="sidebar-right">', '</div>'),
    'props': ('<div id="sidebar-right">', '</div>'), 'small': ('<div id="sidebar-right">', '</div>'),
    'similar': ('<div id="sidebar-right">', '</div>'), 'tree': ('<div id="sidebar-left">', '</div>'),
    'dock': ('<div id="vp-overlay">', '</div>'), 'library': ('<div id="viewport">', '</div>'),
    'fasteners': ('<div id="vp-cmd-host">', '</div>'), 'topbar': ('', ''),
}
parts = {}
for k, h in d['parts'].items():
    a, b = wrap.get(k, ('', ''))
    h = h.replace('assets/help/fasteners-poster.webp', 'ui/fasteners-poster.webp').replace('assets/help/fasteners.webm', 'ui/fasteners.webm')
    h = h.replace('assets/library/', 'library/')
    if k == 'topbar':
        h = re.sub(r'<span class="dtn-a">([^<]*)</span><span class="dtn-b"></span>', lambda m: m.group(1), h)
    if k == 'fasteners':
        h = re.sub(r'<details class="cmd-adv" id="fa-adv">.*?</details>', '', h, flags=re.S)
        h = re.sub(r'<div class="field-help" id="fa-info">.*?</div>', '', h, flags=re.S)
    if k == 'smart':   # shown before the run: the whole scene, 1.1 million triangles
        h = h.replace('552,115 triangles in 42 parts', '1,103,373 triangles in 43 parts').replace('reduce 552,115 triangles to 276,000', 'reduce 1,103,373 triangles to 552,000')
        h = re.sub(r'(id="smart-target" value=")[^"]*(")', r'\g<1>552k\g<2>', h)
    if k == 'props':   # likewise (site.js counts it down when Optimise is pressed)
        h = (h.replace('552,115', '1,103,373').replace('is-reduced', '').replace('width:50.04%', 'width:100%').replace('50.0% of original', '100.0% of original')
             .replace('≈ 13,146 per part', '≈ 25,660 per part').replace('<strong class="prop-value">42</strong>', '<strong class="prop-value">43</strong>')
             .replace('365,912', '668,150').replace('12.2 MB', '22.6 MB'))
    parts[k] = a + h + b
json.dump(parts, open(os.path.join(site, 'ui-parts.json'), 'w', encoding='utf8'), ensure_ascii=False, separators=(',', ':'))

os.makedirs(os.path.join(site, 'ui'), exist_ok=True)
for f in ('fasteners.webm', 'fasteners-poster.webp'):
    shutil.copy(os.path.join(app_help, f), os.path.join(site, 'ui', f))
print('css', len(css) // 1024, 'KB; parts', {k: len(v) for k, v in parts.items()})
