// ========== LAB APPS ==========
// Apps, small tools and web experiments. The Lab page lists them as a shelf
// of cards (lab.js) and each has a page of its own, apps/<id>.html, drawn
// from this same list by app-page.js. Look: apps.css.
//
// To add one: add an object here and copy apps/webtree.html to
// apps/<id>.html, changing the id, title and description in it.
//   id        file name of its page, and its handle everywhere
//   title, subtitle, category
//   stage     how finished it is, shown as a small tag by its name: 'Alpha',
//             'Beta', 'Experimental' (optional)
//   repo      GitHub link            url   where it runs (optional)
//   download  file the Download button fetches (optional; without it the
//             button gets the repo's current code as a zip)
//   icon      image URL (optional; without one the tile shows the initial)
//   stats     the strip under the header: [label, value] pairs
//   cover     wide picture for its post in the Lab feed
//   shots     screenshots: [image, caption] pairs (optional)
//   clips     short silent loops: [name, line, clip.webm] (optional); the poster is <clip>_thumb.webp
//   phone     screenshots taken on a phone, shown tall: [image, caption]
//             pairs (optional)
//   gallery   small square pictures: [image, caption] pairs, titled by
//             galleryTitle (optional)
//   spotlights  "a closer look": big cards, each [name, a line about it,
//             picture, icon name] (optional)
//   about     paragraphs
//   highlights  the headline cards: [big figure, a line about it] (optional)
//   steps     how it works, in order: [name, a line about it] (optional)
//   features  [name, a line about it] pairs, or for a long list
//   featureGroups  [{ title, note, items: [[name, line], …] }, …]
//   start     { text, commands: [[label, command], …] } (optional)
//   changelog { link, versions: [{ version, date, latest, summary,
//             items: [[tag, text], …] }, …] }, newest first (optional)
//   info      the table at the bottom: [label, value] pairs
//   site      an app with a site of its own instead of one page: { path, … }.
//             Its pages (home, features, screenshots, docs, download,
//             changelog) are written into `path` by tools/build-app-site.js
//             from this entry; re-run it after editing. The other keys are
//             what only the site shows: lead, collapse, requirements.
//             Its docs are in <path>docs-content.js
window.labApps = [
  {
    id: 'meshoptimiser',
    title: 'MeshOptimiser',
    subtitle: 'Heavy CAD, made light enough for a browser.',
    category: 'CAD tool',
    stage: 'Beta',
    repo: 'https://github.com/xpayn3/MeshOptimiser',
    icon: 'Images/apps/meshoptimiser-icon.svg',
    cover: 'Images/apps/meshoptimiser-hero.webp',
    shots: [
      ['Images/apps/meshoptimiser-hero.webp', 'A rear derailleur open in MeshOptimiser. The parts tree is on the left, the totals and the clean-up tools on the right.'],
      ['Images/apps/meshoptimiser-viewer.webp', 'Before anything is done: 43 parts and 1.1 million triangles, with the heaviest parts ranked on the right.'],
      ['Images/apps/meshoptimiser-smart-optimise.webp', 'Smart optimise is one button that runs the clean-ups in order. Auto picked Balanced and aims at half the triangles.'],
      ['Images/apps/meshoptimiser-optimised.webp', 'Done. 1,103,373 triangles became 552,115, and what was saved is shown under the number.'],
      ['Images/apps/meshoptimiser-report.webp', 'The report puts the scene as it was opened next to the scene now.'],
      ['Images/apps/meshoptimiser-fasteners.webp', 'Fasteners found twelve bolts and screws by their shape: 129,460 triangles, ready to isolate or delete.'],
      ['Images/apps/meshoptimiser-select-hidden.webp', 'Select hidden parts and its settings, in a card beside the model.'],
      ['Images/apps/meshoptimiser-select-hidden-result.webp', 'One part inside the housing can’t be seen from any side. It is selected: 3,160 triangles.'],
      ['Images/apps/meshoptimiser-isolate.webp', 'That hidden part on its own, isolated.'],
      ['Images/apps/meshoptimiser-smart-fit.webp', 'Smart fit turns a part into a box, a cylinder, a few boxes or blocks.'],
      ['Images/apps/meshoptimiser-blocks.webp', 'Blocks on the two heaviest parts: 172,894 triangles down to 114, and the outline is still there.'],
      ['Images/apps/meshoptimiser-fill-holes.webp', 'Fill holes closes holes in flat faces and leaves the rest alone.'],
      ['Images/apps/meshoptimiser-split.webp', 'Split cuts a mesh that was fused on export back into the solids it was made of.'],
      ['Images/apps/meshoptimiser-stacked-copies.webp', 'Stacked copies finds parts that sit exactly on top of another copy, which flicker where they meet.'],
      ['Images/apps/meshoptimiser-align.webp', 'Align to floor: turn the model in steps and say which side sits at zero.'],
      ['Images/apps/meshoptimiser-clay.webp', 'Clay: every part in one plain material, so only the shape is left.'],
      ['Images/apps/meshoptimiser-xray.webp', 'X-ray: every part as a see-through shell.'],
      ['Images/apps/meshoptimiser-wireframe.webp', 'Wireframe: every edge of every part.'],
      ['Images/apps/meshoptimiser-heatmap.webp', 'Heatmap: parts coloured by how many triangles they carry.'],
      ['Images/apps/meshoptimiser-exploded.webp', 'The exploded view at 40%, with a slider for each axis.'],
      ['Images/apps/meshoptimiser-inspect.webp', 'One part selected: its triangles, its share of the scene and its rank by weight.'],
      ['Images/apps/meshoptimiser-search.webp', 'Search for “bolt” and the bolts in the library come up, ready to add.'],
      ['Images/apps/meshoptimiser-search-sum.webp', 'The same search does sums: 12*25.4 gives 304.8, and Enter copies it.'],
      ['Images/apps/meshoptimiser-context-menu.webp', 'Right-click a part to frame it, isolate it, select similar ones, copy or delete.'],
      ['Images/apps/meshoptimiser-library.webp', 'The library drawer. Click a part, look at it, and set its size before it goes in.'],
      ['Images/apps/meshoptimiser-bolt-nut.webp', 'A hex bolt that brings its own nut, with the nut’s type and distance from the head as settings.'],
      ['Images/apps/meshoptimiser-materials.webp', 'The materials drawer: every material in the scene and how many parts use it.'],
      ['Images/apps/meshoptimiser-export.webp', 'Export as GLB, glTF, FBX, USDZ, OBJ, STL, PLY, or a parts list.'],
      ['Images/apps/meshoptimiser-tabs.webp', 'Every tab is a scene of its own. Drag them into order.'],
      ['Images/apps/meshoptimiser-settings-general.webp', 'Settings, General: start screen, tabs and what asks before it deletes.'],
      ['Images/apps/meshoptimiser-settings-viewport.webp', 'Settings, Viewport: grid, gizmo, fog and the background.'],
      ['Images/apps/meshoptimiser-settings-performance.webp', 'Settings, Performance: the renderer, the quality, and what a moving view gives up.'],
      ['Images/apps/meshoptimiser-shortcuts.webp', 'Every shortcut, searchable.'],
      ['Images/apps/meshoptimiser-start.webp', 'The start screen: drop a file, open a recent one or begin from a shape.'],
    ],
    site: {
      path: 'apps/meshoptimiser/',
      // the search on the page (see searchDemo in tools/build-app-site.js): [name, shortcut / note, detail]
      demo: {
        kicker: 'Try it',
        title: 'Search is how you get around.',
        line: 'This is the app’s own search, filled with a rear derailleur’s parts. Type a part, a library item or a command. The arrow keys move, Enter runs, and it does sums too.',
        start: 'bolt',
        placeholder: 'Search parts, the library, commands, or type a sum',
        hint: '12*25.4 · 2 in · a part’s name',
        tips: [
          ['bolt', 'The bolts in the scene and every bolt in the library, in one list.'],
          ['12*25.4', 'Sums are worked out as you type. Enter copies the answer.'],
          ['2 in', 'A length in inches comes back in millimetres, which is what the scene uses.'],
          ['fill', 'Commands are in the same list, with their shortcuts.'],
        ],
        parts: [
          ['Pivot bolt M5', '', '4,812 triangles'],
          ['Pivot bolt M5 (lower)', '', '4,812 triangles'],
          ['Pulley bolt M5×12', '', '9,360 triangles'],
          ['Limit screw H', '', '3,120 triangles'],
          ['Limit screw L', '', '3,120 triangles'],
          ['B-knuckle bolt M8', '', '6,540 triangles'],
          ['Hanger bolt M10', '', '8,244 triangles'],
          ['Cage plate, outer', '', '165,071 triangles'],
          ['Cage plate, inner', '', '111,460 triangles'],
          ['Upper pulley', '', '109,430 triangles'],
          ['Lower pulley', '', '109,430 triangles'],
          ['Parallelogram link, front', '', '69,962 triangles'],
          ['Parallelogram link, rear', '', '66,860 triangles'],
          ['Spring housing', '', '63,212 triangles'],
          ['Battery cover', '', '32,480 triangles'],
          ['Clutch cam', '', '24,879 triangles'],
          ['B-knuckle', '', '21,736 triangles'],
          ['Pulley bushing', '', '19,052 triangles'],
        ],
        library: [
          ['Hex bolt', '', 'M8 × 30, a parametric part'],
          ['Eye bolt', '', 'M10, a parametric part'],
          ['Carriage bolt', '', 'M8 × 40'],
          ['U bolt', '', 'for a 40 mm tube'],
          ['Socket head screw', '', 'M6 × 20'],
          ['Hex nut', '', 'M8'],
          ['Wing nut', '', 'M8'],
          ['Castle nut', '', 'M10'],
          ['T-slot nut', '', '20 series'],
          ['Spring washer', '', 'M8'],
          ['Hex standoff', '', 'M4 × 12'],
          ['Pillow block', '', 'for a 12 mm shaft'],
          ['Spur gear', '', '24 teeth, module 2'],
          ['Sprocket', '', '16 teeth'],
          ['Stepper motor', '', 'NEMA 17'],
          ['Linear rail', '', '300 mm'],
          ['I beam', '', '100 × 55'],
          ['Box tube', '', '40 × 40'],
          ['Flange', '', 'DN50'],
          ['Pipe elbow', '', 'DN50, 90°'],
        ],
        commands: [
          ['Select fasteners…', '', 'Finds bolts, nuts and washers by their shape'],
          ['Select hidden parts…', '', 'Picks what can’t be seen from outside'],
          ['Smart optimise', '', 'Runs every clean-up in one go'],
          ['Fill holes…', 'P', 'Closes holes in flat faces'],
          ['Split meshes…', 'X', 'Cuts a fused mesh into its solids'],
          ['Smart fit selection', 'Ctrl + B', 'A part becomes a box, a cylinder or blocks'],
          ['Align model to the floor', '', 'Stands the model on the grid'],
          ['Isolate selected', 'S', 'Hides everything but the selection'],
          ['Clay view', '5', 'Every part in one plain material'],
          ['Library', 'Shift + L', 'The drawer of parts to add'],
          ['Export model…', 'Ctrl + E', 'GLB, glTF, FBX, OBJ, STL and more'],
          ['Keyboard shortcuts', '?', 'Every key in the app'],
        ],
      },
      // the library on the page: shelves of [file name in Images, name]; the pictures are the app’s own
      library: {
        kicker: 'The library',
        title: 'Eighty-six parts, one drag away.',
        line: 'Bolts, nuts, pipe fittings, profiles, gears, a stepper motor. Pick a shelf, then drag a part into the scene on the right, or double-click it. In the app each of these is a real part with sizes you can change before it goes in.',
        hint: 'Drag a part here',
        shelves: [
          ['Shapes', [['cube', 'Cube'], ['sphere', 'Sphere'], ['cylinder', 'Cylinder'], ['cone', 'Cone'], ['torus', 'Torus'], ['plane', 'Plane'], ['capsule', 'Capsule'], ['wedge', 'Wedge'], ['pyramid', 'Pyramid'], ['prism', 'Prism'], ['hemisphere', 'Hemisphere'], ['roundedbox', 'Rounded box'], ['halfcyl', 'Half cylinder'], ['tetra', 'Tetrahedron'], ['star', 'Star'], ['plus', 'Cross'], ['arrow', 'Arrow']]],
          ['Fasteners', [['hexbolt', 'Hex bolt'], ['allen', 'Socket head screw'], ['countersunk', 'Countersunk screw'], ['buttonhead', 'Button head screw'], ['threadedrod', 'Threaded rod'], ['eyebolt', 'Eye bolt'], ['washer', 'Washer'], ['pin', 'Dowel pin'], ['rivet', 'Rivet'], ['key', 'Parallel key'], ['standoff', 'Hex standoff'], ['setscrew', 'Set screw'], ['carriagebolt', 'Carriage bolt'], ['ubolt', 'U bolt'], ['circlip', 'Retaining ring'], ['springwasher', 'Spring washer']]],
          ['Nuts', [['hexnut', 'Hex nut'], ['jamnut', 'Thin nut'], ['locknut', 'Lock nut'], ['flangenut', 'Flange nut'], ['capnut', 'Cap nut'], ['castlenut', 'Castle nut'], ['squarenut', 'Square nut'], ['couplingnut', 'Coupling nut'], ['wingnut', 'Wing nut'], ['thumbnut', 'Knurled nut'], ['tslotnut', 'T-slot nut'], ['eyenut', 'Eye nut']]],
          ['Pipes and flanges', [['tube', 'Tube'], ['elbow', 'Pipe elbow'], ['tee', 'Pipe tee'], ['reducer', 'Pipe reducer'], ['endcap', 'Pipe cap'], ['flange', 'Flange'], ['pipecross', 'Pipe cross']]],
          ['Profiles and plates', [['plate', 'Plate'], ['flatbar', 'Flat bar'], ['angle', 'Angle profile'], ['channel', 'U channel'], ['tprofile', 'T profile'], ['zprofile', 'Z profile'], ['ibeam', 'I beam'], ['boxtube', 'Box tube'], ['extrusion', 'T-slot extrusion'], ['roundbar', 'Round bar'], ['hexbar', 'Hex bar'], ['cchannel', 'C channel'], ['gusset', 'Gusset plate'], ['perfplate', 'Perforated plate'], ['slotplate', 'Slotted plate'], ['hinge', 'Hinge']]],
          ['Machine parts', [['gear', 'Spur gear'], ['rack', 'Gear rack'], ['sprocket', 'Sprocket'], ['pulley', 'V pulley'], ['bearing', 'Ball bearing'], ['bushing', 'Flanged bushing'], ['spring', 'Spring'], ['handwheel', 'Handwheel'], ['knob', 'Star knob'], ['bracket', 'Corner bracket'], ['stepper', 'Stepper motor'], ['collar', 'Shaft collar'], ['pillowblock', 'Pillow block'], ['wheel', 'Wheel'], ['rail', 'Linear rail'], ['foot', 'Levelling foot'], ['handle', 'Pull handle'], ['enclosure', 'Enclosure']]],
        ],
      },
      // the design band: the app's own components on a stage ([part, x, y, depth, tilt in degrees, delay in ms],
      // in a 1240 x 920 stage; see designBand in tools/build-app-site.js and ui-parts.json / ui.css), a plan of the window, and its numbers
      design: {
        kicker: 'Design',
        title: 'Every gap is on purpose.',
        lead: 'None of this is a screenshot. Each card, switch, slider and button below is the app’s own markup and stylesheet, lifted out of the running window and put on a stage. Press a switch, drag a slider, hit Optimise.',
        stage: [
          ['topbar', 330, 18, 0.3, 0, 0],
          ['tree', 24, 92, 0.5, -1.4, 80],
          ['props', 930, 60, 0.8, 1.2, 160],
          ['smart', 300, 130, 1.0, -1.2, 240],
          ['explode', 962, 480, 0.9, 1.6, 320],
          ['fasteners', 640, 420, 1.2, 1, 400],
          ['library', 24, 585, 0.7, -0.6, 480],
          ['dock', 190, 858, 1.1, 0, 560],
        ],
        note: 'The real components, drawn at their real size and scaled to fit. Move the pointer over the stage.',
        layout: {
          title: 'The whole window, as a plan',
          line: 'Five areas and nothing else. The tools float over the model instead of squeezing it, so the picture never changes size when you open one.',
          alt: 'A plan of the MeshOptimiser window: a top bar, the parts tree on the left, the viewport in the middle, the properties on the right and a status bar underneath',
          top: 44, left: 248, view: 1200, right: 268, status: 22,
          names: ['Top bar', 'Parts tree', 'Viewport', 'Properties', 'Status bar'],
          notes: [
            ['Top bar', 'Menu and tabs on the left, export on the right. Nothing else competes with the model.'],
            ['Parts tree', 'The same width in every tab, unless you switch that off in Settings.'],
            ['Viewport', 'Cards and the toolbar float over it. The library and the materials drawer slide up from below.'],
            ['Properties', 'Totals first, then the tools in three groups: Inspect, Clean up and Reduce.'],
          ],
        },
        tokens: [
          ['#101010', 'the one background'],
          ['13 px', 'Inter, the body text'],
          ['30 px', 'every toolbar button'],
          ['28 px', 'every number field'],
          ['6 px', 'corner radius of a control'],
          ['10 px', 'corner radius of a card'],
        ],
      },
      // the opening picture as two layers (see popHero in tools/build-app-site.js):
      // the window without its model, and the model cut out, placed at box = [left, top, width] in % of the window
      pop: {
        ui: 'Images/apps/meshoptimiser-hero-ui.webp',
        model: 'Images/apps/meshoptimiser-hero-model.webp',
        v: 4,
        size: [2400, 1551],
        modelSize: [1074, 1231],
        box: [34.46, 18.13, 31.08],
        label: 'A rear derailleur comes out of the MeshOptimiser window and pulls itself apart',
        kicker: 'See what is inside',
        title: 'Pull it apart, and look inside.',
        line: 'This is a real mesh, a rear derailleur in 43 parts, and it comes apart as you scroll. In the app every pin, bolt and bushing has its own row, its own triangle count, and a button to hide it, simplify it or take it out.',
      },
      // the first screen: headline (the subtitle above stays as the line under it), the lead, the page title and the meta description
      headline: 'Make a CAD assembly light enough for the web, on your own computer. Free.',
      titleTag: 'MeshOptimiser — Make a CAD assembly light enough for the web. Free.',
      description: 'Turn a heavy STEP assembly into a small GLB on your own computer. Free and open source, the model never leaves your machine, and you see what you throw away.',
      lead: 'MeshOptimiser opens a heavy CAD assembly, keeps one copy of every part that repeats, lets you take out what nobody will see, and exports a small GLB. It runs on your own computer, so the model never leaves it. Free and open source.',
      // four claims under the opening: [claim, a line about it]
      claims: [
        ['Private', 'The model never leaves your computer. No upload, no account, nothing to sign in to.'],
        ['Free and open', 'MIT licence. No subscription and no seat to buy, and the code is on GitHub for anyone to read.'],
        ['You see what you throw away', 'Every part has its own row. Check what a tool picked before it deletes, undo it, and read a before and after report.'],
        ['Built for CAD assemblies', 'Repeated parts are kept once. Hidden parts are found by looking at the model from every side.'],
      ],
      // a job told in pictures (see storyBand in tools/build-app-site.js); link = [label, docs article]
      story: {
        kicker: 'A common job',
        title: 'Send a customer your product without sending your design.',
        line: 'A customer wants to see what you make. They don’t need the screws inside it, the board under the cover or the way you built it. Take out what they shouldn’t see, keep the rest light, and export one small GLB. All of it happens on your computer, and the STEP file stays where it is.',
        steps: [
          ['Take out what is inside', 'Select hidden parts looks at the model from every side and picks the parts that never show. Look at them on their own, then delete.', 'Images/apps/meshoptimiser-select-hidden-result.webp'],
          ['Take out the hardware', 'Select one bolt, press Select similar, and every copy goes with it. The picture shows the Fasteners tool of the next version, 0.14, which finds them by shape.', 'Images/apps/meshoptimiser-fasteners.webp'],
          ['Simplify what is left', 'Smart fit swaps a detailed part for a box, a cylinder or blocks that keep its outline. Fill holes closes the bolt holes.', 'Images/apps/meshoptimiser-smart-fit.webp'],
          ['Export one small GLB', 'Names stay, triangles shrink. Export, then open the file once more to check that it holds only what you meant to share.', 'Images/apps/meshoptimiser-export.webp'],
        ],
        foot: 'It is not a lock. The outside of your product is still in the file.',
        link: ['Read the guide', 'make-model-safe-to-send'],
      },
      // who it is for: [heading, [lines]] twice (see audienceBand)
      audience: {
        kicker: 'Is it for you?',
        title: 'Who it is for, and who it is not for.',
        link: ['How to get a STEP file from your CAD program', 'cad-files-step-first'],
        yes: ['It is for you if', [
          'You have a STEP assembly and need it in a browser, an AR viewer or a configurator, once or now and then.',
          'You are a small manufacturer, a web developer, a visualiser or an engineer who shares models with customers.',
          'The model has to stay on your computer.',
          'You want to see and choose what is removed, part by part.',
        ]],
        no: ['Not yet, if', [
          'Your files are native SolidWorks, CATIA, NX or Creo files. Export STEP first. The docs have a guide for each program.',
          'You need a pipeline: many files, the same clean-up, every week. The command line converts several STEP files in turn, but clean-ups can’t be saved and replayed yet.',
          'You need levels of detail or baked textures. It writes one level and doesn’t bake textures.',
          'You want to use it in a browser tab with nothing to install. It needs Python 3.10 to 3.12 on your computer.',
        ]],
      },
      // what the pipeline collapses (the README's example)
      collapse: [
        ['400 bolts × 50 KB', '1 mesh × 50 KB + 400 positions'],
        ['80 brackets × 12 KB', '1 mesh × 12 KB + 80 positions'],
        ['500K broken triangles', 'Rebuilt, and the tiny ones dropped'],
        ['320 MB STEP', '11 MB compressed GLB'],
      ],
      requirements: [
        ['Python', '3.10, 3.11 or 3.12. 3.13 doesn’t work yet, because cadquery-ocp doesn’t support it.'],
        ['Browser', 'One with WebGPU: a recent Chrome, Edge, Firefox or Safari.'],
        ['Disk', 'About 2 GB free for the Python environment the first time.'],
        ['Network', 'Not needed to run. The viewer’s libraries come with the app, and only a few rarely used converters are fetched when you ask for them.'],
      ],
    },
    spotlights: [
      ['One button, half the triangles', 'Smart optimise runs every clean-up the app has, in order: empty and broken parts, hidden parts, fasteners, tiny parts, holes in flat faces, and then a reduction to the target you set. On this derailleur it took 1,103,373 triangles down to 552,115 and showed what it had saved. One Ctrl+Z puts it all back.', 'Images/apps/meshoptimiser-optimised.webp', 'cube'],
      ['Bolts, found by their shape', 'Names in a CAD export rarely say what a part is. Fasteners cuts each part across its axis and reads the outline: a round shank with a wider head, six flats around a hole, a flat ring. It finds hex bolts, socket screws, nuts and washers whatever they’re called, and leaves bushings, bearings and O-rings alone. Twelve here, 129,460 triangles.', 'Images/apps/meshoptimiser-fasteners.webp', 'cube'],
      ['172,894 triangles down to 114', 'Smart fit used to turn a bracket into a brick. Blocks rebuilds a part from a coarse grid, so its steps, arms and openings stay where they were. Here it took the two heaviest parts of the derailleur from 172,894 triangles to 114.', 'Images/apps/meshoptimiser-blocks.webp', 'cube'],
      ['A bolt that brings its own nut', 'Tick it on, pick the nut and set how far from the head it sits. The nut is part of the bolt’s own shape, in the bolt’s thread. It’s one part in the tree and one undo step, and it can’t slide off the end.', 'Images/apps/meshoptimiser-bolt-nut.webp', 'cube'],
      ['Pull it apart', 'The exploded view has a slider for each axis, so you can open a gearbox along one direction only. Put it back with one click on the pill next to the camera.', 'Images/apps/meshoptimiser-exploded.webp', 'cube'],
      ['Tabs you can arrange', 'Every tab is a scene of its own, with its own undo history. Drag them into order, save from the tab’s icon, and your sidebars stay where you put them from one scene to the next.', 'Images/apps/meshoptimiser-tabs.webp', 'tree'],
      ['It starts like an app', 'Installed, it opens in a window of its own with no address bar and no browser tabs. Drop a STEP, GLB, glTF, FBX, OBJ, 3MF or STL file anywhere on the start screen, or begin from a shape.', 'Images/apps/meshoptimiser-start.webp', 'upload'],
    ],
    clips: [
      ['Fill holes', 'Bolt holes, slots and pockets in flat faces close a few at a time. Everything else stays as it was.', 'Images/apps/meshoptimiser-clip-fill-holes.webm', 'fill-holes'],
      ['Split', 'A mesh that was fused on export comes apart into the solids it was made of.', 'Images/apps/meshoptimiser-clip-split.webm', 'split'],
      ['Select hidden parts', 'Screws, bearings and brackets inside a housing light up: everything you can’t see from outside.', 'Images/apps/meshoptimiser-clip-select-hidden.webm', 'select-hidden-parts'],
      ['Smart fit', 'A dense part becomes a box, a cylinder, a few boxes or blocks that keep its outline.', 'Images/apps/meshoptimiser-clip-smart-fit.webm', 'smart-fit'],
    ],
    stats: [['Version', '0.20.0'], ['Category', 'CAD tool'], ['Platform', 'Windows · macOS'], ['Runs', 'Locally']],
    about: [
      'Made for the one STEP assembly you have to get onto a web page.',
      'The problem is a practical one. A real STEP file can hold 400 identical bolts, 80 duplicate brackets and half a million broken triangles, and a browser is still expected to draw it. MeshOptimiser reads the assembly, spots the parts that are the same and keeps one mesh with a list of positions, rebuilds the bad geometry, and drops what’s too small to see.',
      'What you get back is a compressed GLB and a viewer to look at it in: the part tree, recolouring, mesh tools, a library of parts to add, and export. It runs on your own machine with Python and a browser, so the model never leaves it, and you choose what goes: every part has a row, every action can be undone, and a report puts the scene as it was opened next to the scene now.',
    ],
    highlights: [
      ['320 MB → 11 MB', 'The README’s example: a STEP assembly down to a compressed GLB.'],
      ['About 10× smaller', 'GLBs shrink that much with Meshopt compression, through gltfpack.'],
      ['1 mesh, many positions', 'Identical parts are found at any rotation or position and drawn once.'],
      ['MIT licence', 'Free and open source. No account, no subscription, nothing to upload.'],
    ],
    steps: [
      ['STEP in', 'Drop a .step or .stp file on the start screen, or run the converter from the command line.'],
      ['Convert', 'OpenCascade reads the whole assembly with its names and colours. Repeated parts become one mesh, surfaces are rebuilt, tiny parts are dropped and the result is compressed.'],
      ['GLB out', 'Open it in the viewer to look around, recolour, reduce, tidy the tree and export.'],
    ],
    featureGroups: [
      { title: 'Convert', note: 'STEP to GLB', items: [
        ['Reads the whole assembly', 'Colours, names and the full part tree come straight out of OpenCascade.'],
        ['Finds repeats', 'The same shape at any angle or position becomes one mesh drawn many times.'],
        ['Rebuilds the surfaces', 'Set the detail in millimetres or as a share of the model’s size, and let it drop what’s too small to matter.'],
        ['Compresses', 'Meshopt, through gltfpack, makes GLBs about ten times smaller.'],
        ['Reads IGES and BREP too', 'The converter and the upload take .iges, .igs, .brep and .brp as well as STEP. IGES keeps the names, colours and layers the file has.'],
        ['A whole folder at once', '--batch converts every CAD file in a folder, one process each so a damaged file can’t stop the run, and writes a table of what happened.'],
        ['Level-of-detail files', '--lod 100,50,25 writes the same model three times, lighter each time, with the same nodes, names and instances.'],
        ['Keeps what the CAD file knew', 'Each node carries its name in the CAD tree, its assembly path, part number, colour, layers and volume, wherever the file has them.'],
        ['One click to start', 'start.bat or start.command sets up Python and opens the browser.'],
        ['Long jobs in the background', 'A big conversion runs as a job and its progress shows in the window.'],
      ] },
      { title: 'Look around', items: [
        ['WebGPU, with WebGL2 as a fallback', 'The renderer can be switched in Settings.'],
        ['Real lighting', 'A studio to reflect, soft shadows in the corners, fog on the floor.'],
        ['Dark parts you can still read', 'A studio to reflect on plain backgrounds and a headlight that follows the view, so black parts keep an edge and a sheen.'],
        ['Click what you see', 'Hover, click and box-select work on the parts you see, copies included.'],
        ['Hide, isolate, solo', 'One key each, to cut the noise and focus.'],
        ['Recolour', 'By group, by material or per part, with a reset.'],
        ['Five ways to see it', 'Solid, wireframe, x-ray, heatmap and clay. Clay shows every part in one plain material; right-click it for porcelain, steel or red wax.'],
      ] },
      { title: 'Clean up', items: [
        ['Smart optimise', 'Runs every clean-up in one go and undoes in one step.'],
        ['Fasteners', 'Finds bolts, screws, nuts and washers by their shape and selects them.'],
        ['Select hidden parts', 'Picks the parts that can’t be seen from outside, ready to delete.'],
        ['Stacked copies', 'Finds parts drawn twice in the same place and keeps one. It only removes a part when an identical one sits in the same place, so 400 placed bolts stay 400.'],
        ['Finds copies in other tools’ files', 'A GLB, FBX, OBJ or 3MF that writes the same bolt out again for every place it is used is searched for repeats when it opens. A 600-mesh test file went from 2.72 MB to 186 KB.'],
        ['Decimate within a distance', 'Type a number of millimetres and triangles go for as long as no point of the surface moves further than that. The result is measured, not trusted.'],
        ['Recipes', 'Smart optimise saves its settings under a name and runs them again later, or hands them to someone as a small file.'],
        ['Merge by colour', 'One mesh per colour for the selection or for everything you can see. One undo.'],
        ['Fill holes', 'Closes bolt holes, slots and pockets in flat faces and leaves the rest. You can set the size, the depth and which kinds of hole.'],
        ['Decimate', 'Reduces the selection by a percentage or to a triangle count, and keeps normals, UVs and vertex colours.'],
        ['Split', 'Brings back the separate solids of a mesh that was fused on export.'],
        ['Smart fit', 'Swaps a part for a simple stand-in: a box, a turned box, a cylinder, a few boxes, or blocks that keep the outline.'],
        ['Fit to budget', 'Give it a triangle count for the whole scene and it reduces the heaviest meshes first, with a preview.'],
        ['Align to floor', 'Stands a model that arrived on its side on the grid.'],
        ['Delete small parts', 'Removes parts too small to see, plus empty, duplicate and broken ones.'],
        ['What it saved', 'Every action shows the triangles it removed, and every part remembers what it arrived with.'],
      ] },
      { title: 'The part tree', items: [
        ['Built for big assemblies', 'Ten thousand rows scroll smoothly, because only the rows you can see are drawn.'],
        ['Search and filters', 'Find parts by name, and tint the small ones.'],
        ['Flatten, dissolve, ungroup', 'Collapse chains of single groups, dissolve a group, or ungroup a branch.'],
        ['Batch rename (F2)', 'Templates, find and replace with regular expressions, and presets.'],
        ['Organise from the right-click menu', 'Take a group out and keep what was in it, flatten a group, sort inside it A to Z or Z to A, move it up or down, delete the empty ones, open or close a whole branch.'],
        ['Groups and parts together', 'Ctrl toggles a row as a unit, Shift picks the range from the last row you clicked, groups and parts alike.'],
        ['Undo and redo', 'Tree edits, recolouring, renames and clean-ups share one history.'],
        ['Right-click menu', 'Hide, isolate, recolour, rename or frame a part from one menu.'],
      ] },
      { title: 'Draw and sweep', note: 'Lines are parts', items: [
        ['A Draw tool (L)', 'Pen, rectangle, circle, arc, polygon, freehand and edit, on the ground, the front, the side, the view or the face of a part.'],
        ['Dots you can snap to', 'A field of dots follows the grid near the pointer and a click a few pixels off still lands on a dot. Handles snap too.'],
        ['Edit any line', 'Drag points and handles, click a curve to add a point, double-click for smooth or sharp. Ctrl-drag breaks a handle from its partner.'],
        ['Round or cut the corners', 'Drag the ring on the corner of a rectangle or polygon and every corner follows. Round or Bevel is one click.'],
        ['A line is a row in the tree', 'Rename it, hide it, group it, nest it, move it with the gizmo. One undo for everything.'],
        ['Properties like Cinema 4D', 'A Shape card for width, radius, sides and corners, and a Spline card with Type, Close and Interpolation: None, Natural, Uniform, Adaptive or Subdivided.'],
        ['Sweep', 'Carry a circle, a rectangle or another line along a path, with scale at both ends, a twist and closed ends. The result is a normal part.'],
      ] },
      { title: 'Build', items: [
        ['A library of 86 parts', 'Bolts, nuts, pipe fittings, profiles, gears and a stepper motor. Look at one, change its size, then drag it in.'],
        ['A bolt with its own nut', 'The nut is part of the bolt, so it moves and undoes with it.'],
        ['Exploded view', 'Pull the parts apart with a slider for each axis.'],
        ['Measure', 'Click two points. The measurements stay in a list and can be picked again.'],
      ] },
      { title: 'Export', items: [
        ['GLB and glTF', 'With Draco or Meshopt compression, and textures embedded if you want them.'],
        ['FBX, USDZ, OBJ, STL, PLY', 'Common 3D and AR formats, with scale presets for mm, cm, m and inches.'],
        ['Parts list', 'A CSV bill of materials: every part and its size.'],
        ['Check against where it’s going', 'Compare the scene with the published guidance for a web page, a Shopify product, Apple AR Quick Look or a phone app, before and after exporting.'],
        ['Save scene', 'Keeps the view, the selection and the recolouring in a small file next to the model.'],
      ] },
      { title: 'The app', items: [
        ['Start screen', 'Drop a file anywhere, open a recent one, or begin from a shape.'],
        ['Scene tabs', 'Each tab is its own scene. Opening a file never replaces one that has something in it.'],
        ['Cards beside the model', 'A tool with settings opens as a card. Enter runs it and Esc puts it away.'],
        ['Numbers you drag', 'Drag any number sideways to change it, or click to type.'],
        ['One Settings window', 'General, viewport, camera, performance, scene and storage, with one search for all of it.'],
        ['Search (Ctrl or ⌘ + K)', 'Every command, every part in the scene and every part in the library.'],
        ['Shortcuts', 'A searchable list of every key.'],
        ['Comes back where you left it', 'Your files and saved scenes are still there after a reload.'],
        ['Looks after itself', 'The server closes with the window, a crash is noticed at the next start and offers Reopen and Safe mode, and a warning shows when the graphics card is not in use.'],
        ['Non-destructive', 'The original geometry isn’t touched until you export.'],
        ['No build step', 'Plain JavaScript and CSS. Edit a file, refresh, done.'],
      ] },
    ],
    start: {
      text: 'The first run sets up its Python environment and downloads what it needs, then opens the viewer. After that it starts in about a second.',
      commands: [
        ['Windows', 'start.bat'],
        ['macOS', './start.command'],
        ['Command line', 'python step2glb.py input.step --meshopt'],
      ],
    },
    changelog: {
      link: 'https://github.com/xpayn3/MeshOptimiser/blob/main/CHANGELOG.md',
      versions: [
        { version: '0.20.0', fixes: 9, date: '9 Oct 2026 · 14:50', latest: true,
          summary: 'You can draw. A Draw tool makes lines and shapes, and they are real parts of the scene: rows in the tree, in groups, moved with the gizmo, with Shape and Spline cards in Properties and a Sweep that turns a path and a profile into a solid. The tree gets organising commands, the converter reads IGES and BREP, copies are found in files from other tools, and the app looks after itself.',
          items: [
            ['New', 'A Draw tool (L). Pen, rectangle, circle, arc, polygon, freehand and edit, in Bezier, Cubic, B-spline or Linear. Place a shape with two clicks and type its size: 20 x 10, Enter. Draw on the ground, the front, the side, the view, or on the face of a part.'],
            ['New', 'Snapping you can see. A field of dots fades in round the pointer, and a click a few pixels off a dot still lands on it. Bezier handles snap to the grid, and Shift snaps the angle in 15° steps.'],
            ['New', 'Edit any line. Drag points and handles, click a curve to add a point, double-click a point for smooth or sharp, Ctrl-drag a handle to break it from its partner. A ring on the corner of a rectangle or polygon rounds or cuts every corner when you drag it.'],
            ['New', 'A line is a part of the scene. It has a row in the tree, so you can rename it, hide it, group it, nest it and move it with the gizmo. Lines open from GLB and glTF files and go back into them.'],
            ['New', 'Properties for lines, as in Cinema 4D. A Shape card (width, radius, sides, corners) and a Spline card: Type, Close Spline, and Interpolation with Points, Angle and Maximum length.'],
            ['New', 'Sweep. Carry a circle, a rectangle or another line along a path, with a scale at both ends, a twist and closed ends. The result is a normal part.'],
            ['New', 'Organise the tree from a group’s right-click menu: Remove group (keep contents), Flatten this group, Sort A to Z and Z to A, Move up and down, Delete empty groups, Expand or Collapse a branch. Ctrl and Shift pick groups and parts together.'],
            ['New', 'The converter reads IGES and BREP, converts a whole folder with --batch, writes LOD files with --lod, and keeps each node’s CAD data in its extras.'],
            ['New', 'Copies are found in files from other tools, so a GLB, FBX, OBJ or 3MF that repeats a bolt a hundred times becomes one mesh. Decimate can work “within” a distance in millimetres, Export can check against a web page, Shopify, AR Quick Look or a phone app, and Smart optimise keeps recipes.'],
            ['New', 'The server closes ten seconds after the last window and takes its converters with it. A crash is noticed at the next start, with Reopen last file and Safe mode, and a warning shows when Chrome is not using the graphics card.'],
            ['Fix', 'Deduplicate geometry no longer deletes real parts. It removed every part whose shape it had seen before, so 400 placed copies of one bolt became one. Now a part goes only when an identical one sits in the same place.'],
            ['Fix', 'Scan whole model no longer freezes the app. It works in slices, with progress and a Cancel button.'],
            ['Fix', 'A leak in Split is closed: each split and undo left about 130 outline shapes on the graphics card.'],
            ['Fix', 'The floor grid is no longer cut off when you zoom in close, and changing the scene scale keeps the view where it was.'],
            ['Fix', 'A slip of the mouse no longer eats a click in the tree. Ctrl and Shift clicks never start a drag, and a press that lets go on its own row is a click.'],
            ['Fix', 'Shift no longer lights up the button you just clicked.'],
            ['Polish', 'The Draw card is compact, and the next tooltip appears at once while one is showing. Smart fit is tidier, and its Advanced section has its own reset button.'],
          ] },
        { version: '0.15.0', date: '9 Oct 2026 · 02:07',
          summary: 'The commands come to the pointer. Hold W and a ring of commands opens round it, four clean-up tools join the list, Untriangulate takes out the triangles that only cut a flat face up, and Dynamic place gets a scale handle.',
          items: [
            ['New', 'Quick wand. Hold W over the viewport and a ring opens round the pointer. Move toward a slice and let go. With a selection it has Hide, Reduce, Delete and More; with nothing selected it has Fit view, Select all, View, Show all, File and Clean.'],
            ['New', 'Repair mesh joins doubled vertices, removes empty and doubled triangles and turns faces so neighbours agree on which side is out. Remove hidden faces deletes the faces that never show: the inside of a housing, where two parts press together.'],
            ['New', 'Merge by material or by group, and Select by rule: rules on a part’s name, material, group, triangles, size, and whether it is shown, flagged or instanced.'],
            ['New', 'Untriangulate turns flat neighbouring triangles into one polygon and cuts it again with the fewest triangles. A flat plate of 200 triangles becomes 38, with no change of shape.'],
            ['New', 'Wireframe is the solid surfaces with a thin black line on every edge, as in Cinema 4D. Settings can show triangles, polygons or only the sharp edges.'],
            ['New', 'Dynamic place has a scale handle: a small cube on the part’s top face that grows or shrinks it evenly, with a ghost of the old size behind.'],
            ['Polish', 'Decimate and Fit to budget look after normals, UVs and vertex colours, and the report says how far the surfaces moved.'],
          ] },
        { version: '0.14.0', fixes: 59, date: '8 Oct 2026 · 23:39',
          summary: 'The biggest round of fixes the app has had. We read the whole code base and tested it hard on assemblies with thousands of parts, and fixed what we found: 59 fixes, most of them in the things you only notice when they go wrong, like undo, exports and big files. Three new tools and a calmer viewport came along.',
          items: [
            ['New', 'Smart optimise. One card, one button, at the top of Reduce. It runs every clean-up the app has, one after another: empty and broken parts, parts hidden inside, bolts and nuts, small parts, holes in flat faces, and a reduction to the triangle count you set. Light, Balanced or Strong, or Auto. The whole run is one undo step.'],
            ['New', 'Fasteners finds bolts, screws, nuts and washers by their shape, whatever they’re called, and selects them. Stacked copies finds parts drawn twice in the same place. Select similar has a strictness slider, from “about the same size” to “the very same shape”.'],
            ['New', 'The library is a drawer under the viewport (Shift + L). Click a part to look at it, turn it, set its size, and then it goes in with those sizes. A starred shelf, small or large tiles.'],
            ['New', 'Drop a file on a scene that already has parts and the app asks: add it here, or open it in a new tab. Right-click a tab for duplicate, close others and recent files. Hold Shift while dragging a handle to snap, and turn the wheel to change the step.'],
            ['Fix', 'Cinema 4D opens the FBX. A binary FBX carries an id, a creation time and a closing code that have to agree, and the FBX SDK refuses the file when they don’t. Ours wrote a random id with a fixed code, so Blender and the app could read it and Cinema 4D couldn’t. They agree now.'],
            ['Fix', 'An FBX now says what its units are and which way is up. A 2.6 m machine used to arrive in Cinema 4D 26 m long, and a Z-up scene was labelled Y-up.'],
            ['Fix', 'The binary FBX shares its materials: one per colour instead of one per mesh. A 778-part model arrived with 778 materials and took 13 seconds to open. Now it has 40 and opens in 1.4 s. OBJ keeps parts that share a name separate: 778 parts used to arrive as 325.'],
            ['Fix', 'Up axis and Scene scale no longer leak into the file for some parts and not others. A part you moved after changing either one used to be written turned or resized while its neighbours weren’t.'],
            ['Fix', 'The local server only answers the app’s own page. Before, any web page open in your browser could send requests to localhost:4242. Folders are no longer listed either, and nothing is served from .git or .venv.'],
            ['Fix', 'Names and scene data from a file are never run as markup. Three places built HTML from them without escaping: measurements saved inside a GLB, the label that follows a dragged tree row, and the Flatten dialog.'],
            ['Fix', 'A fresh install converts STEP again. The OpenCascade package had moved to a version the converter can’t import, so the versions are pinned now, and start.bat installs again when the requirements change or the first install failed.'],
            ['Fix', 'Position, rotation and size show the whole number. The steppers took half the field and the unit sat on top of the digits, so −1091.234 read as −1091.'],
            ['Fix', 'Hidden instanced parts no longer wreck Select all. A hidden copy was built from a zero matrix, and the NaN that came out spread to every selected part. Undo now brings back deleted instanced parts, which used to come back as rows with nothing drawn.'],
            ['Fix', 'Undoing a fit in an exploded view no longer throws parts around, and merging in an exploded view no longer leaves the merged part at the exploded place. Merge now keeps the part where it was in the tree, in the same group and at the same depth.'],
            ['Fix', 'Smart fit no longer fits and moves its neighbours. Parts that shared a shape with a fitted part were fitted with it, and put on its position, if they stood within 5% of the model’s size.'],
            ['Fix', 'The Heavy parts list follows the scene. A part deleted with the Delete key stayed listed, and undo didn’t bring it back.'],
            ['Fix', 'A hidden part kept its selection outline, and a part shown again had none. Every way of hiding and showing now ends with the outline on exactly the selected parts you can see.'],
            ['Fix', 'Delete small parts only looks at parts that are on show, and tells you how many hidden ones it skipped.'],
            ['Fix', 'Less flicker between panels lying on each other. The camera’s near plane now follows the model’s nearest depth, which gives the depth buffer several times the precision at normal distances: 0.001 mm instead of 0.008 mm on a 3.5 m assembly seen from 6.8 m.'],
            ['Fix', 'The 2D views (Top, Front, Side) have their grid back, orbiting out of one returns to the perspective camera, and screenshots from them aren’t stretched.'],
            ['Fix', 'Files with invalid coordinates open. NaN and Infinity become 0, with a notice, where before the camera turned into not-a-number and the viewport never recovered. Broken and empty files get a plain message.'],
            ['Fix', 'FBX files with leftover geometry open directly instead of going through the slower conversion. A geometry attached to nothing, left behind when its object was deleted before export, made the reader give up.'],
            ['Fix', 'Split by proximity can’t freeze the tab on a plate or a box any more. Its grid is bounded now, where one triangle used to fill millions of cells.'],
            ['Fix', 'A colour changed in the material editor is exported and shows on the part’s swatch. Duplicate and Split keep the material a part is wearing. Clay no longer sticks to parts made while it was on.'],
            ['Fix', 'Quit asks about every open scene, not only the one in front. Import no longer turns later Opens into appends, and “Don’t ask again” can be undone in Settings.'],
            ['Fix', 'Settings and Keyboard shortcuts open in front of the start screen. They used to open behind it, so nothing seemed to happen.'],
            ['Fix', 'Switches can be reached with Tab and flipped with Space. Enter presses the button that has focus in a dialog instead of always accepting, and Esc in a dropdown closes only the dropdown. Single-key shortcuts no longer fire behind a dialog.'],
            ['Fix', 'A STEP file with nothing solid in it says so instead of showing a traceback. Cancelling a conversion stops the converter on macOS and Linux too, and a cancel that arrives early isn’t lost.'],
            ['Fix', 'The launchers check for Python 3.10 to 3.12 and say what’s wrong when it’s another version. Starting the app twice opens the window on the server that’s already running. The macOS launchers are executable after a clone.'],
            ['Fix', 'Dozens of smaller ones: Lock on a mixed selection, Find and Replace treating $ as text, OBJ export keeping non-Latin names, ASCII FBX keeping its precision at any scale, the cloner leaving a copy at the centre, redo in the cloner throwing the rest of the redo list away, and more. The full list is on GitHub.'],
          ] },
        { version: '0.13.0', fixes: 1, date: '8 Oct 2026 · 03:04',
          summary: 'It now feels like an app. You can install it, it opens in a window with no address bar or browser tabs, and the title bar can fold away. The scene tabs got better too, and a view that’s moving skips what you couldn’t see anyway.',
          items: [
            ['New', 'Install it from Chrome or Edge and you get a desktop icon and a window of its own. start.bat opens that window directly.'],
            ['New', 'In the installed app you can fold the title bar away. The window buttons float over the corner and the app’s own top bar takes over.'],
            ['New', 'Drag tabs into order. The tab follows the pointer, the others slide aside, and Esc puts it back.'],
            ['Polish', 'Tabs have a dot on the icon (yellow for unsaved, green for saved), a click on the icon saves, and the close button moved to the right end.'],
            ['New', 'Every tab can share the same sidebars, so switching scenes keeps the widths and the folded left sidebar. There’s a switch in Settings to turn it off.'],
            ['Perf', 'While you orbit, parts under about three pixels are skipped, and the resolution only drops if frames get slow. Both come back the moment you stop.'],
            ['Fix', 'Properties no longer jumps when a tag appears. “782 hidden” arriving on Isolate used to push the rest of the card down.'],
            ['Polish', 'The renderer picker moved to Settings, the Menu button lost its arrow, and the loading bar is one flat blue.'],
          ] },
        { version: '0.12.0', fixes: 2, date: '8 Oct 2026 · 01:43',
          summary: 'Until now MeshOptimiser opened a model and made it lighter. From this version it can build too: a drawer of 86 parts to drag in, a sideways model stood up on the floor from one card, a whole scene brought down to a triangle count you type, and dark parts that finally look like something.',
          items: [
            ['New', 'The library drawer has 86 parts on six shelves: hex bolts, socket screws, carriage bolts and U bolts; wing, castle, lock and T-slot nuts; pipe tees, elbows and flanges; I beams, box tube and T-slot extrusion; gears, sprockets, bearings, pillow blocks, a linear rail and a stepper motor.'],
            ['New', 'Drag a part out and a see-through copy follows the pointer, already standing where it will land: flat against the face under it, or upright on the floor. Choose M6 × 24 once and every fastener comes out that size.'],
            ['New', 'A bolt can bring its own nut. Pick a wing nut or a castle nut and set how far from the head it sits. It stays one part with one undo step, and it can’t run off the end of the thread.'],
            ['New', 'Align to floor: files arrive any way up. Turn the model in steps, say which side goes to zero on each axis, and watch it move. Switch it on for every file and you’ll never open a model lying down again.'],
            ['New', 'Select hidden parts finds the screws inside a housing and the board under a cover. Fit to budget takes a triangle count for the whole scene and reduces the heaviest meshes first, with a preview and a Cancel.'],
            ['New', 'Smart fit learned two new shapes. Boxes turns a levelling foot into a slab and a bar. Blocks rebuilds a part from a coarse grid and keeps its steps, arms and openings. A 16,812-triangle drive unit came out at 3,048.'],
            ['New', 'Clay view (5) strips the colour so only the shape is left, in clay, porcelain, steel or red wax. A studio to reflect and a headlight that follows the view give dark parts an edge and a sheen.'],
            ['New', 'Search finds parts by name and library parts (“add flange”), and works out 12*25.4 or 2 in. Every number field can be dragged. The optimisation report puts the scene as it was opened next to the scene now.'],
            ['Fix', 'Parts no longer show through thin covers when you zoom out. Under a sheet-metal cover the parts used to flicker through, worse the further away the camera was, because the depth buffer loses precision with distance. The camera’s near plane now moves away from the model with it.'],
            ['Fix', 'Recent files keep their location after a drag and drop, a re-pick, and when the file has changed size.'],
            ['Polish', 'The right sidebar is grouped into Inspect, Clean up and Reduce, and the selected row in the tree is easier to spot. The section plane is gone.'],
          ] },
        { version: '0.11.0', fixes: 11, date: '7 Oct 2026 · 19:11',
          summary: 'The way you use it changed. Scenes open in tabs, tools show up as cards beside the model instead of sitting in a sidebar, every number can be dragged, and one Settings window replaces the three places that used to hold options. It also fixed a long list of things that went wrong with undo.',
          items: [
            ['New', 'Scene tabs. Each tab has its own scene and its own undo history. New and Open never replace a scene that has something in it, and a spare tab is kept ready so a new one is there at once.'],
            ['New', 'Split (X) and Fill holes (P) open as cards beside the model. Enter runs them, and Esc puts the card away before it clears your selection.'],
            ['New', 'Fill holes got options: through, blind and open holes, a smallest size, a depth limit and a flatness tolerance. It was tested on a very large assembly with nine different sets of options.'],
            ['New', 'Drag any number to change it. Shape parameters take one line each. There’s one Settings window with a search, every command is behind “…”, and the shortcuts no longer clash.'],
            ['New', 'Properties is never empty. With nothing selected it shows the scene’s totals. With a part selected it shows its triangles, what was saved, its share of the scene and its rank by weight.'],
            ['Fix', 'A filled hole can no longer leave a crack. A fill is only accepted if every edge it cuts is covered by a cap and every cap can be closed completely, and the zero-area stitch triangles that CAD meshes carry are removed with the wall they were stitched to.'],
            ['Fix', 'Undoing a group could throw its parts across the scene. A selected part hangs on the move gizmo’s pivot, and the undo entry recorded that pivot as the part’s parent. Redoing “group a group” also moved everything inside it.'],
            ['Fix', 'Hide selected (H) is an undo step now. It had none, so Ctrl+Z after H undid whatever came before it.'],
            ['Fix', 'Material names keep up. A new material is named after its colour instead of a random code, the name follows the colour, and applying or undoing a preset while the editor is open refreshes the editor.'],
            ['Fix', 'A scene made only of added shapes showed 0 triangles in the status bar. The status bar and Properties gave different sizes for the same mesh right after loading, and both now count shared geometry once.'],
            ['Fix', 'The four shape tiles on the start screen all showed the torus, because their thumbnails were rendered at the same time through one shared mesh.'],
            ['Fix', 'Dragging a number could go on following the mouse after you let go, and a click didn’t always put the caret in the field. Tooltips inside a card appeared instantly and cut off after the first words; they wait now and show the whole tip.'],
            ['Polish', 'A darker, calmer interface in one tone. The GPU path tracer is gone, and nothing is fetched from a CDN at start-up.'],
          ] },
        { version: '0.10', fixes: 17, date: '7 Oct 2026 · 15:37 and 15:47',
          summary: 'Faster, with tools it didn’t have before: a hole filler that can tell a hole from a boss, a materials drawer, a decimator that keeps normals and UVs, background workers, and a part tree that keeps up with five million triangles. And a long list of things that were quietly wrong in the tree. Version 0.10.1 followed ten minutes later with one change: the libraries the viewer needs now come with the app, so it starts without a CDN and works with no connection at all.',
          items: [
            ['Fix', 'The tree hides nothing. A group used to vanish from the hierarchy as soon as it had no live parts, although it still existed. Every group is listed now, and one with nothing in it says “empty”.'],
            ['Fix', 'Deleting a group deletes the group. Delete on a selected group, and “Delete group” in the menu, remove the row with its contents, and one undo brings both back.'],
            ['Fix', 'The parts tree scrolls in one direction, with the eye and colour column staying lined up. Rows used to be as wide as their own text, so the eyes of short rows slid around when you scrolled sideways.'],
            ['Fix', 'Import and Append keep the existing tree instead of moving every part into “Untraced”. A failed load no longer turns the next Open into an append.'],
            ['Fix', 'A second geometry edit on the same part could stop the viewport from drawing at all, with an error on every frame. The WebGPU renderer decides what to upload by comparing attribute names and version numbers, and a freshly built geometry looked unchanged to it. Every tool that swaps geometry now stamps it.'],
            ['Fix', 'Every remaining editing gap now has an undo: values typed into the transform panel, tree drag and drop, the eye icon on a group, every other visibility toggle, and the materials panel.'],
            ['Fix', 'Hiding and showing reach instanced parts everywhere: the eye icon, Hide unselected, group toggles and hide by colour.'],
            ['Fix', 'Cloner copies are exported and saved. Only the source part used to be written.'],
            ['Fix', 'Cancel stops a STEP conversion. The loader’s Cancel ends the polling and stops the converter on the server, so a conversion can’t finish later and replace your scene.'],
            ['Fix', 'The move readout showed “Y +0.00” and “Z +0.00” while you dragged a rotated part, because it read the travel along the wrong axes. It follows the gizmo’s own axes now.'],
            ['Fix', 'In a small window the right sidebar was pushed off the edge. The column shrinks now, and the status bar drops the vertex and memory counts, then the file name, before anything else.'],
            ['Fix', 'Collapsing and re-expanding a group no longer brings back the rows of deleted parts, and adding a shape highlights the new part in the tree instead of the previous one.'],
            ['Fix', 'The icon set is pinned to one version (0.10.1). It used to load as “latest”, so an upstream release could rename or drop an icon without warning.'],
          ] },
        { version: '0.9.0', fixes: 24, date: '7 Oct 2026 · 12:41',
          summary: 'More trustworthy. A self-test that runs inside the app, undo for every action, exports that match the scene, and a restyled interface. This was the version where we stopped trusting that things worked and started checking.',
          items: [
            ['New', 'A self-test that runs inside the app and checks the things that broke before.'],
            ['Fix', 'Decimate destroyed parts. The removal count was taken from the un-indexed corner count, three per triangle, instead of the welded vertex count, so at −50% most parts were reduced to zero triangles. Now −25, −50 and −75% remove exactly that share.'],
            ['Fix', 'Decimate never reached the export. The reduced geometry wasn’t registered under the part’s hash, so export, merge and the memory readout still used the original mesh.'],
            ['Fix', 'Save scene lost its state. The marker node was flagged invisible and the exporter skips invisible objects, so the camera, view settings, hidden parts and measurements were never written. Save scene also mangled node names and wrapped the scene in one more group on every save and reopen.'],
            ['Fix', 'Exporting in Wireframe, X-ray or Heatmap baked the view mode into the file. Export and Save scene now run in Solid and put the view back afterwards.'],
            ['Fix', 'Recenter and Center pivot didn’t reach the export, so the file kept the old positions. Bake transforms also displaced parts that sat under a moved parent, and a part that shared its buffer with another (any duplicate) was transformed twice or moved a part you hadn’t selected.'],
            ['Fix', 'PLY export hung on “Preparing export…” whenever the tab was in the background. Hidden instanced parts exported with NaN transforms.'],
            ['Fix', 'Six tools pushed no undo entry, so Ctrl+Z reverted an older, unrelated action: Decimate, Recenter on origin, Bake transforms, Center pivot, Recompute normals and Delete empty groups. All six undo and redo now. Undo of Isolate, Show all and Hide unselected restores instanced parts as well.'],
            ['Fix', 'Flatten and “Delete empty groups” work from the tree now. Selecting a part moves its mesh out of its group in the scene graph, and both tools trusted the scene graph. Grouping parts from different levels no longer pulls the outside part into the first part’s group.'],
            ['Fix', 'Delete acted on the scene behind an open dialog, and Ctrl+S also toggled Isolate. Global shortcuts are ignored while a dialog is open or a dropdown has focus.'],
            ['Fix', 'The ruler only measured on Ctrl+click while the hint said “Click two points”. A plain click picks now, and picking no longer changes the selection.'],
            ['Fix', 'Shift-click range no longer sweeps up rows hidden by a search or a collapsed group. “% of model” showed 173% for a single cube. Three sidebar cards wouldn’t collapse. A few shortcut hints were wrong.'],
          ] },
        { version: '0.8.0', fixes: 9, date: '11 May 2026 · 17:20',
          summary: 'The groundwork got modern: a ray-marched floor grid, one keycap style on every shortcut, undo rebuilt as a flat list of commands, and all the CSS that was injected at runtime moved into the stylesheet.',
          items: [
            ['New', 'A ray-marched ground grid. It stays sharp at any distance, doesn’t shimmer when you orbit, and doesn’t fight with the model for depth.'],
            ['New', 'A new Shortcuts overlay with a sticky search, category headers, two columns and one keycap per key of a combination. Press ? to open it.'],
            ['Polish', 'One keycap style on the hint strip, the tooltips, the command palette, the brand menu and the Shortcuts overlay. Smart fit and its arrow are one control now.'],
            ['Refactor', 'Eight pieces of CSS that were injected at runtime (about 490 lines) moved into the stylesheet, and eleven undo patches became one registry covering 21 operations.'],
            ['Fix', 'The grid shimmered by a pixel or two when you orbited, because the camera-follow moved the mesh by sub-pixel amounts every frame. The cube on the grid no longer fights it for depth.'],
            ['Fix', 'The tree summary stayed at “1 parts in hierarchy” after a delete because it counted deleted parts too. A group’s origin dot no longer gets stranded in space when every part in it is deleted.'],
            ['Fix', 'The group button no longer asks for a name, and the path tracer no longer throws an error into the console on an empty scene.'],
            ['Fix', 'Three bugs in the materials panel: adding a material toasted a confusing hint, duplicating one needed a part selected for no reason, and merging left the absorbed materials in the list as ghosts and leaked their GPU memory.'],
          ] },
        { version: '0.7.0', date: '11 May 2026 · 13:12', summary: 'A GPU path tracer with a render window that builds up samples, a hint strip that follows what you’re doing, an add-a-shape picker on long press, a standalone Cloner you can drag parts into, and Revert to source.' },
        { version: '0.6.0', fixes: 3, date: '11 May 2026 · 09:18',
          summary: 'A live Cloner in the style of Cinema 4D, a Ctrl-click measure tool, an origin marker for every group, a two-panel Export window, simplification and Meshopt on by default, and mouse buttons that work the way CAD programs expect.',
          items: [
            ['Fix', 'Face winding. Only truly reversed faces are flipped now. The old check also flipped internal and external faces and left back-face artefacts on cellular geometry.'],
            ['Fix', 'Two different shapes could end up with the same hash, so a cube and its diagonal mirror were treated as one. They aren’t any more.'],
            ['Fix', 'The size readout of a Meshopt-compressed GLB was blind, because the library that read it can’t decode compressed files. It reads the file’s own header now.'],
          ] },
        { version: '0.5.0', fixes: 1, date: '8 May 2026 · 14:35',
          summary: 'Scene management (New scene, Import and merge, Scene settings), parametric shapes with millimetre inputs, transforms that know their units, backgrounds without banding, and a clean shutdown.',
          items: [
            ['Fix', 'The Transform panel refreshes after a shape is rebuilt, so the numbers match the new geometry instead of staying on the old ones.'],
          ] },
        { version: '0.4.0', fixes: 4, date: '7 May 2026 · 18:57',
          summary: 'HDRI lighting, an endless floor grid with fog, parametric shapes, a camera pill with Ctrl or ⌘ + 1 to 4, popups without borders, and a refreshed blue.',
          items: [
            ['Fix', 'The right-click menu in the viewport was completely broken: another handler cancelled every right-click before the app’s menu could build. It works again.'],
            ['Fix', 'Going back to an HDRI background after loading another one gave a black scene. A rapid edit of a shape’s parameters could crash the renderer on a buffer race.'],
            ['Fix', 'Tooltips no longer get stranded on screen when a popup opens, a dialog shows, the window loses focus, or a panel slides in over the button.'],
          ] },
        { version: '0.3.0', fixes: 5, date: '7 May 2026 · 03:22',
          summary: 'A full material editor with shader-ball previews, a scale gizmo that snaps with Shift and shows live values, screenshots at any size, Top, Front and Side views, and a rescue path for old FBX files.',
          items: [
            ['Fix', 'Saving a screenshot fired the save dialog twice and wrote a 0-byte PNG. A save that was refused, or locked by OneDrive, silently dropped the file; all three failures now fall back to a normal download.'],
            ['Fix', 'Textures leaked memory every time you swapped models. They’re all released now, and material thumbnails fall back to a simple 2D drawing when WebGL isn’t there, instead of blank tiles.'],
            ['Fix', 'Copy, Paste and Select All work again on every number and text field. A custom right-click had been eating them everywhere.'],
          ] },
        { version: '0.2.0', date: '6 May 2026 · 20:58', summary: 'The editing side arrived: a start screen, a command palette, a shortcuts overlay, settings, section planes, a switchable renderer, batch rename, flatten, dissolve and ungroup, undo and redo, and Save scene. Expanding and collapsing a tree of 10,000 nodes went from about a second to under 10 ms.' },
        { version: '0.1.0', date: '5 May 2026 · 21:30', summary: 'The first public commit: the STEP to GLB pipeline, the WebGPU viewer with the part tree, picking, hide, isolate and colouring by group, the local server, one-click launchers, and bundled Draco and Assimp decoders.' },
      ],
    },
    info: [
      ['Status', 'Before 1.0, so things may still change'],
      ['Platform', 'Windows, macOS'],
      ['Requires', 'Python 3.10 to 3.12, a browser with WebGPU, about 2 GB free for the first install'],
      ['Built with', 'cadquery-ocp, trimesh, numpy, Draco, Assimp (WASM), WebGPU, plain JavaScript'],
      ['Licence', 'MIT'],
      ['First published', '5 May 2026'],
      ['Source', 'github.com/xpayn3/MeshOptimiser'],
    ],
  },
  {
    id: 'webtree',
    title: 'Windy Tree',
    subtitle: 'A real-time procedural tree generator.',
    category: '3D tool',
    stage: 'Alpha',
    repo: 'https://github.com/xpayn3/webtree',
    url: 'https://xpayn3.github.io/webtree/',
    icon: 'https://xpayn3.github.io/webtree/icons/icon.svg',
    cover: 'Images/apps/windytree-editor.webp',
    shots: [
      ['Images/apps/windytree-editor.webp', 'The editor: a cherry tree with its trunk, shape and branching controls'],
      ['Images/apps/windytree-oak.webp', 'The oak preset'],
      ['Images/apps/windytree-japanese-maple-leaves.webp', 'Leaf count, size, season and material, on a red Japanese maple'],
      ['Images/apps/windytree-pine-conifer.webp', 'Conifers get their own crown and needle controls'],
      ['Images/apps/windytree-bark-closeup.webp', 'Procedural bark, from presets down to fissure depth'],
      ['Images/apps/windytree-leaf-closeup.webp', 'Close in on branches and individual leaves'],
      ['Images/apps/windytree-wind.webp', 'Wind: strength, gusts, direction and turbulence'],
      ['Images/apps/windytree-lighting-presets.webp', 'Eight lighting presets, here on moonlight'],
      ['Images/apps/windytree-light-theme-scale.webp', 'A light studio backdrop, with a 1.8 m figure for scale'],
      ['Images/apps/windytree-wireframe.webp', 'Wireframe view shows the generated mesh'],
      ['Images/apps/windytree-spline-view.webp', 'Spline view shows the branch skeleton'],
      ['Images/apps/windytree-command-palette.webp', 'Find any slider or command from the palette'],
      ['Images/apps/windytree-context-menu.webp', 'Right-click the canvas for quick actions'],
      ['Images/apps/windytree-export-mesh.webp', 'Export the tree as OBJ, STL, GLB or glTF'],
    ],
    galleryTitle: 'Species presets',
    stats: [['Category', '3D tool'], ['Platform', 'Web'], ['Presets', '35'], ['Engine', 'WebGPU']],
    gallery: ['oak', 'willow', 'palm', 'baobab', 'japanesemaple', 'birch', 'pine', 'cherry', 'olive', 'redwood', 'ginkgo', 'cypress']
      .map(name => [`https://xpayn3.github.io/webtree/presets/${name}.png`, name === 'japanesemaple' ? 'Japanese maple' : name]),
    about: [
      "An experiment in growing trees from numbers.",
      "Nothing in it is modelled by hand. Trunk, bark, branching, leaves, moss and vines all come from parameters, and a tree is shaped by changing them: pick a species, sculpt the branches, set the wind and the light. Every parameter can be found from a single search box.",
      "It is built on WebGPU and Three.js and runs in the browser. A finished tree can be exported.",
    ],
    highlights: [
      ['35', 'Species presets, in three families: broadleaf, conifer and bush.'],
      ['180+', 'Parameters, from trunk lean to leaf wax sheen, all searchable.'],
      ['4', 'Levels of detail per tree, exported together as one bundle.'],
      ['0', 'Things to install. Open the link in a WebGPU browser.'],
    ],
    spotlights: [
      ['Pick a species', 'Start from one of 35 presets, grouped into broadleaf, conifer and bush, or reopen a recent tree.', 'Images/apps/windytree-species.webp', 'leaf'],
      ['Sculpt mode', 'Reshape branches by hand with a right-drag. Wind and physics pause while you sculpt, and you can discard to undo everything in one go.', 'Images/apps/windytree-sculpt.webp', 'pointer'],
      ['LOD editor', 'Build lower-detail versions of the tree, see the triangle count of each, and export the chain as one .glb bundle.', 'Images/apps/windytree-lod.webp', 'layers'],
      ['Scene settings', 'Camera, environment and physics, renderer, shadows and post effects, plus your saved presets and mesh export.', 'Images/apps/windytree-scene.webp', 'sun'],
    ],
    steps: [
      ['Pick a species', 'Choose a preset to start from, or begin with a blank custom tree.'],
      ['Shape it', 'Tune the sliders for trunk, branching, foliage and bark, or switch to Sculpt and move branches by hand.'],
      ['Export', 'Save a mesh, a level-of-detail bundle, a screenshot, or the preset itself.'],
    ],
    featureGroups: [
      { title: 'The tree', items: [
        ['Trunk', 'Height, lean, twist, taper, root flare, buttresses and knots.', 'tree'],
        ['Branching levels', 'Each level has its own count, angles, forks, gravity and curve; add, copy or remove levels.', 'tree'],
        ['Bark', 'Procedural fissures, bands, patches and grain, with moss on top.', 'mesh'],
        ['Leaves and needles', 'Arrangement, size, droop and season, with a leaf material that has transmission and wax sheen.', 'leaf'],
        ['Fruits, flowers and vines', 'Optional extras, plus dead-wood stubs and canopy dieback to age a tree.', 'spark'],
        ['Crown and pruning', 'Crown silhouette, clean bole, pruning and gravity sag.', 'slice'],
      ] },
      { title: 'Shaping and motion', items: [
        ['Sculpt mode', 'Right-drag branches to reshape them by hand, with undo.', 'pointer'],
        ['Wind', 'Stiffness, damping, mass and wind response decide how each branch moves.', 'wind'],
        ['Regenerate', 'A variation seed and one key (R) give a new tree from the same settings.', 'refresh'],
        ['Your own leaves', 'Upload a leaf texture and use it on the tree.', 'upload'],
      ] },
      { title: 'Viewing', items: [
        ['Light and sky', 'Sun direction, an HDR sky, and light and dark themes.', 'sun'],
        ['Wireframe and spline views', 'See the mesh, or the tree as its underlying curves.', 'mesh'],
        ['Scale reference', 'A 1.8 m human figure to judge size against.', 'eye'],
        ['Command search', 'Fuzzy-search every parameter, species and action.', 'command'],
      ] },
      { title: 'Export', items: [
        ['Mesh export', 'OBJ, or GLB / glTF for the full mesh and scene.', 'download'],
        ['LOD bundle', 'A chain of lower-detail versions in one .glb.', 'layers'],
        ['Presets', 'Save your own with thumbnails, or copy a preset as JSON.', 'bookmark'],
        ['PNG screenshot', 'Save the current view as a picture.', 'aperture'],
        ['Installable', 'Ships a web app manifest, so it can be added to a device like an app.', 'phone'],
      ] },
    ],
    start: {
      text: 'Open the link in Chrome, Edge or Safari 18+, pick a species and start shaping. The controls:',
      commands: [
        ['Orbit', 'Drag'],
        ['Zoom', 'Scroll'],
        ['Bend a branch', 'Right-drag'],
        ['Regenerate', 'R'],
        ['Wireframe', 'W'],
        ['Leaves on / off', 'L'],
        ['Light / dark', 'T'],
        ['All controls', '?'],
      ],
    },
    info: [
      ['Platform', 'Chrome, Edge or Safari 18+ (needs WebGPU)'],
      ['Built with', 'WebGPU, Three.js'],
      ['Exports', 'OBJ, GLB / glTF, PNG, preset JSON'],
      ['First published', 'April 2026'],
      ['Source', 'github.com/xpayn3/webtree'],
    ],
  },
  {
    id: 'cycleiq',
    title: 'CycleIQ',
    subtitle: 'A cycling training dashboard, powered by intervals.icu.',
    category: 'Fitness',
    stage: 'Experimental',
    repo: 'https://github.com/xpayn3/cyclingHUB',
    url: 'https://xpayn3.github.io/cyclingHUB/',
    icon: 'https://xpayn3.github.io/cyclingHUB/icon-192.png',
    cover: 'Images/apps/cycleiq-workouts.webp',
    shots: [
      ['Images/apps/cycleiq-workouts.webp', 'Workout Builder: recommended, indoor and outdoor sessions'],
      ['Images/apps/cycleiq-routes.webp', 'Route Builder: plan a ride on a 3D terrain map'],
      ['Images/apps/cycleiq-workout-editor.webp', 'The workout editor: an interval session with its power profile'],
      ['Images/apps/cycleiq-workout-editor-light.webp', 'The same editor in the light theme'],
      ['Images/apps/cycleiq-weather-forecast.webp', 'Weather: saved locations, the hourly forecast and the temperature curve'],
      ['Images/apps/cycleiq-weather-ride-score.webp', '7-day forecast with a ride score for today, in the Tour de France theme'],
      ['Images/apps/cycleiq-weather-day-detail.webp', 'A forecast day opened: hourly wind, rain and the best window to ride'],
      ['Images/apps/cycleiq-tire-pressure.webp', 'The tire pressure calculator in My Garage'],
      ['Images/apps/cycleiq-themes.webp', 'Settings: app theme and map style'],
      ['Images/apps/cycleiq-accent-color.webp', 'Accent colour: twelve presets or any custom colour'],
    ],
    phone: [
      ['Images/apps/cycleiq-weather-phone.webp', 'Weather'],
      ['Images/apps/cycleiq-workout-editor-phone.webp', 'Workout editor'],
      ['Images/apps/cycleiq-badge-card-phone.webp', 'An achievement badge as a 3D card'],
      ['Images/apps/cycleiq-tire-pressure-phone.webp', 'Tire pressure calculator'],
    ],
    stats: [['Category', 'Fitness'], ['Platform', 'Web · installable'], ['Pages', '22'], ['Badges', '28']],
    about: [
      "A training dashboard for cycling, built on intervals.icu.",
      "It reads rides from intervals.icu (and Strava) and lays them out in one place: training load, power analysis, goals and streaks, weather, a garage for the bikes, and builders for workouts and routes.",
      "Everything runs in the browser, and the account details never leave it.",
    ],
    highlights: [
      ['22', 'Pages, from the dashboard to a lifetime heatmap of everywhere you have ridden.'],
      ['28', 'Achievement badges, each a holographic 3D card you can spin.'],
      ['Offline', 'Works without a connection after the first load, map tiles included.'],
      ['4', 'Themes: dark, light, editorial and custom.'],
    ],
    spotlights: [
      ['Workout Builder', 'Design intervals visually from warm-up, steady, interval, ramp and cool-down blocks, then export a Zwift .zwo file.', 'Images/apps/cycleiq-workouts.webp', 'pulse'],
      ['Route Builder', 'Click to add waypoints on a 3D terrain map, get auto-routing on the road network and an elevation profile, and export GPX or FIT.', 'Images/apps/cycleiq-routes.webp', 'globe'],
      ['Connect and sync', 'Link an intervals.icu account, use a setup link, or restore from a JSON backup. Only new activities are fetched after the first sync.', 'Images/apps/cycleiq-connect.webp', 'refresh'],
    ],
    featureGroups: [
      { title: 'Training', items: [
        ['Dashboard', 'Weekly stats, a fitness snapshot and recent rides in widgets you can reorder and hide.', 'grid'],
        ['Fitness and training load', 'CTL, ATL and TSB over any date range, FTP history, wellness insights and race prediction.', 'pulse'],
        ['Power analysis', 'Power curve, time in zones, a power profile radar and W′ balance.', 'spark'],
        ['Activity detail', 'A 3D terrain map with power, heart rate, cadence, speed and elevation charts, intervals and climbs detected.', 'globe'],
        ['Goals and streaks', 'Week, day and month streaks, a 52-week calendar heatmap, and targets with progress rings.', 'bookmark'],
        ['Compare', 'One period against another, side by side, with the change in each metric.', 'layers'],
      ] },
      { title: 'Planning', items: [
        ['Workout Builder', 'A visual interval designer with power and heart rate targets, exported as Zwift .zwo.', 'pulse'],
        ['Route Builder', 'Waypoints, auto-routing, gradient bands and GPX / FIT export.', 'globe'],
        ['Calendar', 'Month and week views with planned rides and training plans.', 'grid'],
        ['Weather', 'A 7-day forecast with ride-quality badges, an hourly breakdown and a wind rose.', 'sun'],
        ['What-if tools', 'A tapering wizard, a CTL simulator, race pacing and a fuelling plan.', 'spark'],
      ] },
      { title: 'Gear', items: [
        ['My Garage', 'Your bikes with photos, components, service history and wear.', 'cube'],
        ['Battery monitoring', 'Garmin, SRAM AXS and coin-cell batteries, with estimated drain.', 'pulse'],
        ['Tire pressure calculator', 'SRAM / Zipp, Silca and Berto models.', 'drop'],
      ] },
      { title: 'Under the hood', items: [
        ['Offline and installable', 'A service worker caches the app and up to 3,000 map tiles.', 'phone'],
        ['3D badge cards', 'Procedural cards with holographic materials, a moving spotlight and drag momentum.', 'cube'],
        ['Device sync', 'Peer-to-peer between your devices, paired with a QR code.', 'refresh'],
        ['Backup', 'Export and import everything as one JSON file.', 'download'],
        ['Design system', '150+ design tokens and four themes.', 'code'],
      ] },
    ],
    start: {
      text: 'CycleIQ needs an intervals.icu account for its data. Three steps to connect:',
      commands: [
        ['1', 'In intervals.icu, open Settings → API'],
        ['2', 'Copy your Athlete ID'],
        ['3', 'Show the API key, copy it, and paste both into CycleIQ'],
      ],
    },
    info: [
      ['Data', 'intervals.icu, Strava'],
      ['Also uses', 'Open-Meteo (weather and air quality), Nominatim (place names), MapLibre (maps)'],
      ['Platform', 'Any modern browser; installable as an app'],
      ['Privacy', 'Credentials are stored locally in your browser only'],
      ['First published', 'February 2026'],
      ['Source', 'github.com/xpayn3/cyclingHUB'],
    ],
  },
];

// The app's icon tile: its picture, or its initial when it has none.
window.labAppIcon = function (app) {
  const tile = document.createElement('span');
  tile.className = 'app-icon';
  if (app.icon) {
    const img = document.createElement('img');
    Object.assign(img, { src: app.icon, alt: '', decoding: 'async' });
    tile.appendChild(img);
  } else {
    tile.classList.add('is-letter');
    tile.textContent = app.title.charAt(0);
  }
  return tile;
};
