// ========== IMAGE & PROJECT DATA ==========
// Wrapped in an IIFE so top-level `const IMG` / `const projects` etc. don't
// collide with home.js (which has its own local `const projects` array) or
// script.js when all three execute in the shared script scope.
(function () {
const IMG = 'Images';

const projects = {
  cestel: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'CESTEL Animation',
    year: 2023,
    client: 'Cestel',
    collab: 'Studio ENKI',
    location: 'Slovenia, Ljubljana',
    desc: [
      'With over 30 years of experience in bridge weigh-in-motion measurements, bridge assessments and traffic data, Cestel is one of the world\'s leading companies in the fields of high-speed weigh-in-motion and traffic analysis.',
      'Animation that showcases CESTEL measurement process in an abstract way that is engaging for the watchers. Animation will be used for informational purposes and showcase of their system.'
    ],
    brief: 'Visualize a complex measurement system in an engaging, accessible way.',
    tools: ['Cinema 4D', 'Redshift', 'Sound Design', 'Photoshop', 'AfterEffects'],
    images: [
      `${IMG}/Cestel_project/cestel_anim_01_v.webm`,
      `${IMG}/Cestel_project/Cestel_image_01.webp`,
      `${IMG}/Cestel_project/Cestel_image_02.webp`,
      `${IMG}/Cestel_project/cestel_anim_02_v.webm`,
      `${IMG}/Cestel_project/Cestel_image_03.webp`,
      `${IMG}/Cestel_project/Cestel_image_04.webp`,
      `${IMG}/Cestel_project/Cestel_image_05.webp`,
      `${IMG}/Cestel_project/Cestel_image_06.webp`,
      `${IMG}/Cestel_project/Cestel_image_07.webp`,
      `${IMG}/Cestel_project/cestel_anim_03_v.webm`,
      `${IMG}/Cestel_project/Cestel_image_08.webp`,
      `${IMG}/Cestel_project/Cestel_image_09.webp`,
      `${IMG}/Cestel_project/Cestel_image_10.webp`,
      `${IMG}/Cestel_project/Cestel_image_11.webp`,
      `${IMG}/Cestel_project/Cestel_image_12.webp`,
      `${IMG}/Cestel_project/cover_still.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 1, imgs: [3] },
      { cols: 3, imgs: [4, 5, 6] },
      { cols: 2, imgs: [7, 8] },
      { cols: 1, imgs: [9] },
      { cols: 3, imgs: [10, 11, 12] },
      { cols: 2, imgs: [13, 14] },
    ]
  },
  grounded2022: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2022',
    year: 2022,
    client: 'Pritličje',
    theme: 'Responsibility',
    desc: ['A bold visual system built from the ground up for Grounded 2022. We developed the complete identity through 3D renders, animated teasers, and projection-mapped visuals — crafting every element to feel immersive and unmistakably Grounded.'],
    brief: 'Create a complete visual identity for the 2022 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2022/Grounded_2022_01.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_02.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_03.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_04.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_05.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_06.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_07.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_08.webp`,
      `${IMG}/Grounded_2022/GR_main_1.webm`,
      `${IMG}/Grounded_2022/GR_main_vertical.webm`,
      `${IMG}/Grounded_2022/Projection_CD.webm`,
      `${IMG}/Grounded_2022/najava_landscape.webm`,
      `${IMG}/Grounded_2022/najava_square.webm`,
      `${IMG}/Grounded_2022/najava_vertical.webm`,
      `${IMG}/Grounded_2022/card_holo.webm`,
    ],
    layout: [
      { cols: 1, imgs: [8] },
      { cols: 2, imgs: [0, 1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 1, imgs: [10] },
      { cols: 2, imgs: [7, 9] },
      { cols: 2, imgs: [11, 12] },
      { cols: 1, imgs: [13] },
      { cols: 1, imgs: [14] },
    ]
  },
  grounded2021: {
    color: 'gray',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2021: The State',
    year: 2021,
    client: 'Pritličje',
    desc: ['We shaped the entire visual world of Grounded 2021 — from poster series and sticker packs to social media templates and animated Instagram stories. Every asset was designed to feel cohesive, kinetic, and alive.'],
    brief: 'Design every visual touchpoint — from posters to animated stories.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2021/Grounded_IG.webm`,
      `${IMG}/Grounded_2021/Grounded_SerijaPlakatov.webp`,
      `${IMG}/Grounded_2021/GR_render0034.webp`,
      `${IMG}/Grounded_2021/Grounded_instagram-profil.webp`,
      `${IMG}/Grounded_2021/Grounded_nalepke.webp`,
      `${IMG}/Grounded_2021/Grounded_spletnastran.webp`,
      `${IMG}/Grounded_2021/InstagramStoryAnimation.webp`,
      `${IMG}/Grounded_2021/Statika_1.webp`,
      `${IMG}/Grounded_2021/Statika_2_1.webp`,
      `${IMG}/Grounded_2021/Statika_teme_2.webp`,
      `${IMG}/Grounded_2021/Grounded_2021_insta2.webm`,
      `${IMG}/Grounded_2021/Grounded_2021_post.webm`,
      `${IMG}/Grounded_2021/Grounded_FBcover.webm`,
      `${IMG}/Grounded_2021/Story 3.webm`,
      `${IMG}/Grounded_2021/izvajalci_render_2.webm`,
      `${IMG}/Grounded_2021/GR_anim_web.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 3, imgs: [3, 4, 5] },
      { cols: 2, imgs: [6, 7] },
      { cols: 1, imgs: [8] },
      { cols: 1, imgs: [9] },
    ]
  },
  taf: {
    color: 'blue',
    category: ['Motion', '3D', 'Photogrammetry'],
    name: "The Athlete's Foot",
    year: 2021,
    client: "The Athlete's Foot",
    type: '#worldsneakerday',
    desc: ["We brought sneaker culture to life through high-energy 3D animation and motion graphics for The Athlete's Foot. Every frame was crafted to stop the scroll — bold compositions, dynamic camera work, and product renders that make you want to reach through the screen."],
    brief: 'Make sneaker product launches stop the scroll on social media.',
    tools: ['Cinema 4D', 'AfterEffects', 'Photoshop', 'Substance 3D'],
    images: [
      `${IMG}/Athletesfoot/taf_anim_v.webm`,
      `${IMG}/Athletesfoot/taf_image_01.webp`,
      `${IMG}/Athletesfoot/taf_image_02.webp`,
      `${IMG}/Athletesfoot/taf_image_03.webp`,
      `${IMG}/Athletesfoot/screenshot_01.webp`,
      `${IMG}/Athletesfoot/screenshot_02.webp`,
      `${IMG}/Athletesfoot/screenshot_03.webp`,
      `${IMG}/Athletesfoot/screenshot_04.webp`,
      `${IMG}/Athletesfoot/taf_vertical.webm`,
      `${IMG}/Athletesfoot/taf_landscape.webm`,
      `${IMG}/Athletesfoot/puma.webp`,
    ],
    layout: [
      { cols: 1, imgs: [9] },
      { cols: 1, imgs: [0] },
      { cols: 3, imgs: [1, 2, 3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 2, imgs: [6, 7] },
      { cols: 1, imgs: [8] },
    ]
  },
  grounded2020: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded: Truth',
    year: 2020,
    client: 'Pritličje',
    link: 'https://www.grounded.si',
    desc: [
      'Solidarity, elimination of inequality and peaceful co-existence assume the existence of truth, and truthfulness as the value of public action. In the post-truth world, these assumptions no longer exist.',
      'Those in positions of power often lie without legal or other social sanction. The ruling party-owned media spreads lies about those who resist them. Social networks increase the reach of conspiracy theories, while platforms are placed in the role of arbiters of truth.'
    ],
    brief: 'Build an identity around truth and resistance in a post-truth era.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2020/Grounded_poster_2.webp`,
      `${IMG}/Grounded_2020/Artboard-26.webp`,
      `${IMG}/Grounded_2020/Artboard-26-copy-2.webp`,
      `${IMG}/Grounded_2020/grounded_resnica.webp`,
      `${IMG}/Grounded_2020/Grounded2020_anim_v.webm`,
      `${IMG}/Grounded_2020/Grounded2020_2_anim_v.webm`,
      `${IMG}/Grounded_2020/grounded2020_ekran.webm`,
      `${IMG}/Grounded_2020/grounded2020_fence.webm`,
      `${IMG}/Grounded_2020/grounded2020_mikrofon.webm`,
    ],
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 1, imgs: [6] },
      { cols: 2, imgs: [7, 8] },
    ]
  },
  grounded2018: {
    color: 'blue',
    category: ['Print', 'Branding'],
    name: 'Festival Grounded 2018',
    year: 2018,
    client: 'Pritličje',
    desc: ['The second edition of Grounded explored intimacy in the digital age. We translated that tension into a visual identity — layered renders, glowing textures, and a typographic system that felt both human and synthetic.'],
    brief: 'Translate the tension of digital intimacy into a festival identity.',
    tools: ['Cinema 4D', 'Photoshop', 'Illustrator'],
    images: [
      `${IMG}/Grounded_2018/plakat.webp`,
      `${IMG}/Grounded_2018/grounded_2018_anim_v.webm`,
      `${IMG}/Grounded_2018/44396997_2300717590163245_3256152537651807309_n.webp`,
      `${IMG}/Grounded_2018/Grounded_2018_instagram.webm`,
      `${IMG}/Grounded_2018/Grounded_2018_music.webm`,
      `${IMG}/Grounded_2018/Grounded_2018_03.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
    ]
  },
  tamtam: {
    color: 'blue',
    category: ['Print'],
    name: 'Mesta pešcem — TamTam',
    year: 2018,
    award: 'Mestni plakat leta — TamTam 2018',
    desc: ['A poster that won City Poster of the Year at TamTam 2018. We combined bold typography with layered urban imagery to deliver a message about pedestrian-first cities — a single sheet that sparked conversation across Ljubljana.'],
    brief: 'Design a city poster that sparks conversation about pedestrian rights.',
    tools: ['Photoshop', 'Illustrator'],
    images: [
      `${IMG}/TamTam_Hoja--moj-transport_plakat-tisk.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
    ]
  },
  ment: {
    color: 'purple',
    category: ['Motion', '3D'],
    name: 'AppointMENT 4.0',
    year: 2019,
    desc: ['We designed the complete visual identity for AppointMENT 4.0 — a music and arts event where every visual element, from posters to digital assets, was built around abstract 3D forms and experimental typography.'],
    brief: 'Build a visual identity for a music and arts event from scratch.',
    tools: ['Cinema 4D', 'Photoshop', 'Illustrator'],
    images: [
      `${IMG}/AppointMENT_4.0/AppointMENT_poster.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
    ]
  },
  halloween: {
    color: 'purple',
    category: ['Photogrammetry', '3D', 'Motion'],
    name: "Halloween — The Athlete's Foot",
    year: 2021,
    client: "The Athlete's Foot",
    desc: ['For The Athlete\'s Foot Halloween campaign, we built an entire dark universe from scratch — grotesque characters, fog-drenched environments, and cinematic product shots that turned a seasonal retail push into something people actually wanted to watch.', 'The technical backbone of this project was photogrammetry. Every sneaker was hand-scanned using a DSLR rig — roughly 200–300 photos per shoe, shot from every conceivable angle under controlled lighting. Those images were then processed into raw point clouds, millions of vertices that captured every stitch, crease, and texture detail of the physical product.', 'From there, the real work began. Each point cloud was imported into ZBrush for cleanup — removing noise, filling gaps, rebuilding topology into something render-ready. The poly counts were enormous. A single shoe could easily hit 8–10 million polygons before decimation, and the full scenes with characters and environments pushed workstations to their absolute limits.'],
    brief: 'Turn a seasonal retail campaign into something cinematic and shareable.',
    tools: ['Cinema 4D', 'ZBrush', 'Redshift', 'AfterEffects', 'Substance 3D'],
    images: [
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_01.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_02.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_03.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_04.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_05.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_06.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_07.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_1.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_2.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_3.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_zbrush.webp`,
      `${IMG}/Athletesfoot_halloween/halloween_banner.webm`,
      `${IMG}/Athletesfoot_halloween/halloween_story.webm`,
      `${IMG}/Athletesfoot_halloween/adidas_zx_lowpoly.webp`,
      `${IMG}/Athletesfoot_halloween/DSC_0213.webp`,
      `${IMG}/Athletesfoot_halloween/DSC_9820.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 3, imgs: [1, 2, 3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 2, imgs: [6, 10] },
      { cols: 3, imgs: [7, 8, 9] },
    ]
  },
  blackfriday: {
    color: 'gray',
    category: ['Motion', '3D'],
    name: "Black Friday — The Athlete's Foot",
    year: 2021,
    client: "The Athlete's Foot",
    desc: ['High-impact 3D animation for The Athlete\'s Foot Black Friday campaign. We created explosive product reveals and kinetic type sequences — everything engineered for maximum visual punch in a crowded retail moment.'],
    brief: 'Maximum visual impact for a crowded Black Friday retail moment.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Substance 3D'],
    images: [
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_anim_01.webp`,
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_anim_02.webp`,
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_01.webp`,
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_02.webp`,
      `${IMG}/Athletesfoot_blackfriday/bftaf.webm`,
    ],
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 3] },
    ]
  },
  largavida: {
    color: 'orange',
    category: ['Print', 'Branding'],
    name: 'LargaVida Limited Edition',
    year: 2022,
    desc: ['We designed the complete visual language for LargaVida\'s limited edition release — from packaging to digital presence. Clean, premium, and built to stand out on shelf and screen alike.'],
    brief: 'Design premium packaging and digital presence for a limited release.',
    tools: ['Photoshop', 'Illustrator'],
    images: [
      `${IMG}/LargaVida/01_larga_vida_desktop.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_01.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_02.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_03.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_04.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
    ]
  },
  newedge: {
    color: 'white',
    category: ['Print'],
    name: 'NewEdge Magazine',
    year: 2020,
    desc: ['We crafted the editorial design system for NewEdge — a magazine that bridges digital culture and print craft. Every spread was treated as a composition, balancing bold imagery with refined typography.'],
    brief: 'Create an editorial design system bridging digital culture and print.',
    tools: ['InDesign', 'Photoshop', 'Illustrator'],
    images: [
      `${IMG}/NewEdge_magazine/NewEdge_magazine_01.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_magazine_02.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_magazine_03.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_magazine_04.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_reality_01.webm`,
      `${IMG}/NewEdge_magazine/NewEdge_reality_02.webm`,
    ],
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 3] },
      { cols: 2, imgs: [4, 5] },
    ]
  },
  grounded2023: {
    color: 'blue',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2023',
    year: 2023,
    client: 'Pritličje',
    desc: ['Visual identity, 3D animation and motion design for the Grounded festival 2023 edition.'],
    brief: 'Visual identity and 3D animation for the 2023 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/Grounded_2023/Grounded_2023_01.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_02.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_03.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_04.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_05.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_06.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_07.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 1, imgs: [3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 1, imgs: [6] },
    ]
  },
  grounded2025: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2025',
    year: 2025,
    client: 'Pritličje',
    desc: ['Visual identity and motion design for the Grounded festival 2025 edition.'],
    brief: 'Visual identity and motion design for the 2025 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/Grounded 2025/gr2025cover.webp`,
      `${IMG}/Grounded 2025/Grounded_2025_web.webm`,
      `${IMG}/Grounded 2025/IG_story_01.webm`,
      `${IMG}/Grounded 2025/IG_story_02.webm`,
      `${IMG}/Grounded 2025/IG_story_03.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 1, imgs: [1] },
      { cols: 3, imgs: [2, 3, 4] },
    ]
  },
  grounded2024: {
    color: 'blue',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2024',
    year: 2024,
    client: 'Pritličje',
    desc: ['Visual identity and motion design for the Grounded festival 2024 edition.'],
    brief: 'Visual identity and motion design for the 2024 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2024/Grounded_2024_01.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_02.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_03.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_04.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_05.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_06.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_07.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_sticker_01.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_sticker_02.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_comp.webm`,
      `${IMG}/Grounded_2024/Grounded_2024_story.webm`,
      `${IMG}/Grounded_2024/Grounded_2024_mehurcki.webm`,
    ],
    layout: [
      { cols: 1, imgs: [9] },
      { cols: 2, imgs: [0, 1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 1, imgs: [10] },
      { cols: 2, imgs: [5, 6] },
      { cols: 2, imgs: [7, 8] },
      { cols: 1, imgs: [11] },
    ]
  },
  radenci: {
    color: 'orange',
    category: ['Motion'],
    name: 'Radenci — Prostorska Projekcija',
    year: 2022,
    desc: ['An immersive projection mapping installation in Radenci — transforming architectural surfaces into living canvases. We designed and rendered every visual sequence, syncing light, motion, and space into a single experience.'],
    brief: 'Transform architectural surfaces into a living projection experience.',
    tools: ['Cinema 4D', 'AfterEffects'],
    images: Array.from({ length: 31 }, (_, i) => {
      const names = [
        'P1_S1_K01_0323.webp','P1_S1_K02_0533.webp','P1_S1_K02_i1_0460.webp',
        'P1_S2_K04_0110.webp','P1_S2_K05_0238.webp','P1_S3_K03_0282.webp',
        'P1_S3_K05_0054.webp','P1_S3_K06_0150.webp','P1_S3_K06_0329.webp',
        'P1_S3_K07_0377.webp','P1_S3_K07_0406.webp','P2_S02_K03_0118.webp',
        'P2_S02_K03_0529.webp','P2_S1_K01_0227.webp','P2_S1_K01_A&B_0046.webp',
        'P2_S1_K02_0806.webp','P2_S1_K03_0182.webp','P2_S1_K03_B_i1_0397.webp',
        'P2_S2_K01_0376.webp','P2_S2_K01_0701.webp','P2_S2_K01_0841.webp',
        'P2_S3_K03_0482.webp','P2_S3_K03_B_02_0605.webp','P2_S3_K05_0026.webp',
        'P2_S3_K05_0477.webp',
        'IMG_4065.webp','IMG_4069.webp','IMG_4073.webp',
        'IMG_4075.webp','IMG_4100.webp','IMG_4101.webp'
      ];
      return `${IMG}/Radenci_prostorska_projekcija/${names[i]}`;
    }),
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 3, imgs: [7, 8, 9] },
      { cols: 2, imgs: [10, 11] },
      { cols: 3, imgs: [12, 13, 14] },
      { cols: 2, imgs: [15, 16] },
      { cols: 3, imgs: [17, 18, 19] },
      { cols: 2, imgs: [20, 21] },
      { cols: 3, imgs: [22, 23, 24] },
      { cols: 3, imgs: [25, 26, 27] },
      { cols: 3, imgs: [28, 29, 30] },
    ]
  },
  lab: {
    color: 'gray',
    category: ['Lab'],
    name: 'Lab — Experiments',
    desc: ['Personal experiments, 3D explorations, and creative coding projects.'],
    tools: ['Cinema 4D', 'Houdini', 'Redshift'],
    images: [
      `${IMG}/Lab/Fly_fico.webm`,
      `${IMG}/Lab/Furry_jezik.webm`,
      `${IMG}/Lab/gold.webm`,
      `${IMG}/Lab/Particles2.webm`,
      `${IMG}/Lab/lab_comp.webm`,
      `${IMG}/Lab/lab_impol.webm`,
      `${IMG}/Lab/lab_sandunes.webm`,
      `${IMG}/Lab/Dream_01.webp`,
      `${IMG}/Lab/Dream_02.webp`,
      `${IMG}/Lab/Dream_03.webp`,
      `${IMG}/Lab/Dream_03-2.webp`,
      `${IMG}/Lab/Dream_04-2.webp`,
      `${IMG}/Lab/lab_kristal.webm`,
      `${IMG}/Lab/lab_kristal_story.webm`,
      `${IMG}/Lab/kristal0020.webp`,
      `${IMG}/Lab/kristal0025.webp`,
      `${IMG}/Lab/kristal0026.webp`,
      `${IMG}/Lab/qurtz0012.webp`,
      `${IMG}/Lab/qurtz0033.webp`,
      `${IMG}/Lab/testgoba_3.webp`,
      `${IMG}/Lab/take_3_0138.webp`,
      `${IMG}/Lab/Kersnikova_logo_take4_4.webp`,
      `${IMG}/Lab/end.webp`,
      `${IMG}/Lab/lm62ZTf.webp`,
      `${IMG}/Lab/lab_flag.webm`,
      `${IMG}/Lab/mecha.webp`,
      `${IMG}/Lab/mecha_02.webp`,
      `${IMG}/Lab/mecha_03.webp`,
      `${IMG}/Lab/mecha_04.webp`,
      `${IMG}/Lab/mecha_grid_8.webp`,
      `${IMG}/Lab/mecha_grid_9.webp`,
      `${IMG}/Lab/mecha_grid_11.webp`,
      `${IMG}/Lab/LaLuna_test_RUN.webm`,
      `${IMG}/Lab/ENKI-screensaver_1.webm`,
      `${IMG}/Lab/kersnikova_logo_preview.webm`,
      `${IMG}/Lab/scandianvian.[0000-0244].webm`,
      `${IMG}/Lab/Short_napis 16-9_2.webm`,
      `${IMG}/Lab/222.webp`,
      `${IMG}/Lab/hand.webp`,
      `${IMG}/Lab/legs.webp`,
      `${IMG}/Lab/face.webp`,
      `${IMG}/Lab/zadni_2.webp`,
      `${IMG}/Lab/puma.webp`,
      `${IMG}/Lab/Bossplast_smoke.webp`,
      `${IMG}/Lab/BF.webp`,
      `${IMG}/Lab/Bossplast.webp`,
      `${IMG}/Lab/2880x1560.webp`,
      `${IMG}/Lab/car.webm`,
    ],
    layout: [
      { cols: 1, imgs: [47] },
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 4] },
      { cols: 1, imgs: [5] },
      { cols: 2, imgs: [3, 6] },
      { cols: 3, imgs: [7, 8, 9] },
      { cols: 2, imgs: [10, 11] },
      { cols: 1, imgs: [12] },
      { cols: 2, imgs: [13, 14] },
      { cols: 3, imgs: [15, 16, 17] },
      { cols: 2, imgs: [18, 19] },
      { cols: 1, imgs: [20] },
      { cols: 2, imgs: [21, 22] },
      { cols: 2, imgs: [23, 24] },
      { cols: 1, imgs: [25] },
      { cols: 2, imgs: [26, 27] },
      { cols: 3, imgs: [28, 29, 30] },
      { cols: 2, imgs: [31, 32] },
      { cols: 1, imgs: [33] },
    ]
  },
  kersnikova: {
    color: 'pink',
    category: ['Print', 'Branding'],
    name: 'Kersnikova',
    year: 2021,
    desc: ['We developed the visual identity and print collateral for Kersnikova — posters, brochures, and spatial graphics that translate the institution\'s experimental spirit into bold, accessible design.'],
    brief: 'Translate an experimental institution\'s spirit into accessible design.',
    tools: ['Photoshop', 'Illustrator', 'InDesign'],
    images: [
      `${IMG}/Kersnikova/Plakat-500x700-B2.webp`,
      `${IMG}/Kersnikova/slika nova.webp`,
      `${IMG}/Kersnikova/zlozenka2.webp`,
      `${IMG}/Kersnikova/zvocnik_finished.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 1, imgs: [3] },
    ]
  },
  natureta_renders: {
    color: 'yellow',
    category: ['3D'],
    name: 'Natureta Product Renders',
    year: 2023,
    desc: ['Photorealistic 3D product renders for Natureta — each jar, label, and surface rendered with obsessive attention to material and light. We created visuals that blur the line between photography and CGI.'],
    brief: 'Create photorealistic product renders that rival studio photography.',
    tools: ['Cinema 4D', 'Redshift', 'Photoshop'],
    images: [
      `${IMG}/Natureta product renders/izdelki.webp`,
      `${IMG}/Natureta product renders/Mockup_2.webp`,
      `${IMG}/Natureta product renders/float_2.webp`,
      `${IMG}/Natureta product renders/kumarica.webp`,
      `${IMG}/Natureta product renders/vsi_2.webp`,
      `${IMG}/Natureta product renders/ETA_animacija_FINAL_2_2.webp`,
      `${IMG}/Natureta product renders/Kozarec_eta0001.webp`,
      `${IMG}/Natureta product renders/Kozarec_eta0013.webp`,
      `${IMG}/Natureta product renders/Kozarec_eta0015.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
      { cols: 1, imgs: [5] },
      { cols: 3, imgs: [6, 7, 8] },
    ]
  },
  natureta: {
    color: 'orange',
    category: ['3D', 'Branding'],
    name: 'Natureta 100 Let',
    year: 2023,
    desc: ['Visual design celebrating 100 years of Natureta — we crafted a campaign that honors the brand\'s heritage while feeling fresh and contemporary. From concept to final delivery, every detail was considered.'],
    brief: 'Celebrate 100 years of heritage while feeling fresh and modern.',
    tools: ['Photoshop', 'Cinema 4D'],
    images: [
      `${IMG}/Natureta/Prebranec-Natureta-657f495f8b596.webp`,
      `${IMG}/Natureta/Prebranec-1-65708119051a5.webp`,
      `${IMG}/Natureta/Prebranec-2-657081193738f.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
    ]
  },
  accbox: {
    color: 'blue',
    category: ['Motion', '3D'],
    name: 'AccountingBox',
    year: 2024,
    client: 'AccountingBox',
    desc: ['Motion graphics system for AccountingBox — a suite of short product animations built to explain features across social, web, and in-app surfaces. Each loop is crafted to feel part of the same world: consistent timing, color, and motion language so the product tells one story wherever it shows up.'],
    brief: 'Explain accounting software features through a consistent motion system.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/AccountingBox/4_loop.webm`,
      `${IMG}/AccountingBox/intro.webm`,
      `${IMG}/AccountingBox/freetrial.webm`,
      `${IMG}/AccountingBox/hiter.webm`,
      `${IMG}/AccountingBox/kjerkoli.webm`,
      `${IMG}/AccountingBox/kjerkoli_prvomesto.webm`,
      `${IMG}/AccountingBox/kjerkoli_drugomesto.webm`,
      `${IMG}/AccountingBox/podpora.webm`,
      `${IMG}/AccountingBox/1_loop.webm`,
      `${IMG}/AccountingBox/2_intro.webm`,
      `${IMG}/AccountingBox/6_intro.webm`,
      `${IMG}/AccountingBox/racunovodje_cover_final.webp`,
      `${IMG}/AccountingBox/Podjetja_cover.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [11, 12] },
      { cols: 1, imgs: [1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 1, imgs: [7] },
      { cols: 3, imgs: [8, 9, 10] },
    ]
  },
};

const COLOR_HEX = {
  red: '#e74c3c', orange: '#e67e22', yellow: '#f1c40f', green: '#2ecc71',
  cyan: '#00bcd4', blue: '#3498db', purple: '#9b59b6', pink: '#e91e8a',
  black: '#222222', white: '#e0e0e0', gray: '#888888',
};

// Build flat list of grid items: one per image, tagged with project/year
// Color gets filled in async after image loads
const gridItems = [];
const gridExclude = /screenshot|zbrush|Mockup|larga_vida_screenshot/i;
for (const [projId, proj] of Object.entries(projects)) {
  for (const src of proj.images) {
    if (gridExclude.test(src)) continue;
    gridItems.push({
      src,
      project: projId,
      projectName: proj.name,
      year: proj.year,
      color: proj.color || 'gray',
      category: proj.category || [],
    });
  }
}

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
shuffle(gridItems);

// Expose shared data to other scripts (script.js, overlay.js, home.js)
window.IMG = IMG;
window.projects = projects;
window.COLOR_HEX = COLOR_HEX;
window.gridItems = gridItems;
window.gridExclude = gridExclude;
})();
