// ========== IMAGE & PROJECT DATA ==========
// Wrapped in an IIFE so top-level `const IMG` / `const projects` etc. don't
// collide with script.js, which shares the page's script scope.
(function () {
const IMG = 'Images';

const projects = {
  cestel: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'CESTEL Animation',
    year: 2023,
    client: 'Cestel',
    collab: 'Studio ENKI',
    location: 'Slovenia, Ljubljana',
    desc: [
      "With over 30 years of experience in bridge weigh-in-motion measurements, bridge assessments and traffic data, Cestel is one of the world's leading companies in the fields of high-speed weigh-in-motion and traffic analysis.",
      "The brief was a system nobody ever sees: sensors bolted under a bridge, quietly weighing every truck that drives over it. We decided not to explain it like a manual. The film treats the hardware as product design, with slow macro passes over brushed aluminium, the red sensor housing and the cable gland, and then pulls back to show what those parts are for.",
      "Everything sits in one restrained palette: cool, overcast greys with Cestel's red as the only accent, so the eye always knows where the measurement is happening. Red is the signal. It glows under the axle as a truck crosses, travels down the cable, and becomes the readout and the bars of the traffic chart.",
      "The abstraction is deliberate. A bridge is reduced to a portal, traffic to coloured blocks, weight to a stack of discs pressing on a plate. That let us keep the engineering honest while staying readable for someone who has never heard of weigh-in-motion. Sound design carries the rest: each cut lands on a mechanical click or a low pass of tyres.",
    ],
    brief: 'Visualize a complex measurement system in an engaging, accessible way.',
    tools: ['Cinema 4D', 'Redshift', 'Sound Design', 'Photoshop', 'AfterEffects'],
    images: [
      `${IMG}/Cestel_project/cestel_anim_01_v.webm`,
      `${IMG}/Cestel_project/Cestel_image_01.webp`,
      `${IMG}/Cestel_project/Cestel_image_02.webp`,
      `${IMG}/Cestel_project/cestel_anim_02_v.webm`,
      `${IMG}/Cestel_project/Cestel_image_03.webp`,
      `${IMG}/Cestel_project/Cestel_image_04.webp`,
      `${IMG}/Cestel_project/Cestel_image_05.webp`,
      `${IMG}/Cestel_project/Cestel_image_06.webp`,
      `${IMG}/Cestel_project/Cestel_image_07.webp`,
      `${IMG}/Cestel_project/cestel_anim_03_v.webm`,
      `${IMG}/Cestel_project/Cestel_image_08.webp`,
      `${IMG}/Cestel_project/Cestel_image_09.webp`,
      `${IMG}/Cestel_project/Cestel_image_10.webp`,
      `${IMG}/Cestel_project/Cestel_image_11.webp`,
      `${IMG}/Cestel_project/Cestel_image_12.webp`,
      `${IMG}/Cestel_project/cover_still.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 1, imgs: [3] },
      { cols: 3, imgs: [4, 5, 6] },
      { cols: 2, imgs: [7, 8] },
      { cols: 1, imgs: [9] },
      { cols: 3, imgs: [10, 11, 12] },
      { cols: 2, imgs: [13, 14] },
    ]
  },
  grounded2022: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2022',
    year: 2022,
    client: 'Pritličje',
    theme: 'Responsibility',
    desc: [
      "The 2022 theme was responsibility, Odgovornost. We asked where responsibility usually ends up in everyday life, and the answer was packaging: the warning label, the tamper seal, the small print nobody reads. So the identity is built from objects that promise to look after you.",
      "A pill bottle sealed with a holographic sticker. A scratched disc in a jewel case, carrying every certification logo we could fit on it. A fuel-brand badge redrawn as Grounded Premium. Each one is modelled and lit like a product shot on pure black, so the only colour comes from the hologram foil shifting as the object turns.",
      "The typography follows the objects. The wordmark runs around the rim of the disc and the seal, set tight in a wide grotesque, and the Slovenian and English words cross each other like a target. From there the system stretched across posters, animated teasers and projection visuals without ever needing a new idea, only a new object.",
    ],
    brief: 'Create a complete visual identity for the 2022 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2022/Grounded_2022_01.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_02.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_03.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_04.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_05.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_06.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_07.webp`,
      `${IMG}/Grounded_2022/Grounded_2022_08.webp`,
      `${IMG}/Grounded_2022/GR_main_1.webm`,
      `${IMG}/Grounded_2022/GR_main_vertical.webm`,
      `${IMG}/Grounded_2022/Projection_CD.webm`,
      `${IMG}/Grounded_2022/najava_landscape.webm`,
      `${IMG}/Grounded_2022/najava_square.webm`,
      `${IMG}/Grounded_2022/najava_vertical.webm`,
      `${IMG}/Grounded_2022/card_holo.webm`,
    ],
    layout: [
      { cols: 1, imgs: [8] },
      { cols: 2, imgs: [0, 1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 1, imgs: [10] },
      { cols: 2, imgs: [7, 9] },
      { cols: 2, imgs: [11, 12] },
      { cols: 1, imgs: [13] },
      { cols: 1, imgs: [14] },
    ]
  },
  grounded2021: {
    color: 'gray',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2021: The State',
    year: 2021,
    client: 'Pritličje',
    desc: [
      "Država, The State. For this edition we wanted an image with the weight of a public monument and none of its certainty. The key visual is a single sculpture: figures piled on a rock in the sea, scales in one hand, a halo of swords behind the head, chains and smoke around the base. It borrows the language of official statuary and lets it come apart.",
      "We rendered it twice, once in soft dusk colour and once in polished chrome on black, and those two moods became the whole system. A custom-feeling display face with sharp, ceremonial letterforms does the announcing; a plain geometric sans carries line-ups and dates. Pink against black keeps it loud on a wall and legible on a phone.",
      "The frame with notched corners holds every format together: posters, stickers, the website header, the artist announcements and the animated stories. A black flag reading Država, planted in a red field under the moon, closes the set. It is the same world, just quieter.",
    ],
    brief: 'Design every visual touchpoint — from posters to animated stories.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2021/Grounded_IG.webm`,
      `${IMG}/Grounded_2021/Grounded_SerijaPlakatov.webp`,
      `${IMG}/Grounded_2021/GR_render0034.webp`,
      `${IMG}/Grounded_2021/Grounded_instagram-profil.webp`,
      `${IMG}/Grounded_2021/Grounded_nalepke.webp`,
      `${IMG}/Grounded_2021/Grounded_spletnastran.webp`,
      `${IMG}/Grounded_2021/InstagramStoryAnimation.webp`,
      `${IMG}/Grounded_2021/Statika_1.webp`,
      `${IMG}/Grounded_2021/Statika_2_1.webp`,
      `${IMG}/Grounded_2021/Statika_teme_2.webp`,
      `${IMG}/Grounded_2021/Grounded_2021_insta2.webm`,
      `${IMG}/Grounded_2021/Grounded_2021_post.webm`,
      `${IMG}/Grounded_2021/Grounded_FBcover.webm`,
      `${IMG}/Grounded_2021/Story 3.webm`,
      `${IMG}/Grounded_2021/izvajalci_render_2.webm`,
      `${IMG}/Grounded_2021/GR_anim_web.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 3, imgs: [3, 4, 5] },
      { cols: 2, imgs: [6, 7] },
      { cols: 1, imgs: [8] },
      { cols: 1, imgs: [9] },
    ]
  },
  taf: {
    color: 'blue',
    category: ['Motion', '3D', 'Photogrammetry'],
    name: "The Athlete's Foot",
    year: 2021,
    client: "The Athlete's Foot",
    type: '#worldsneakerday',
    desc: [
      "Sneaker posts all look the same: one shoe, three-quarter view, a drop shadow. For World Sneaker Day we wanted the opposite of a catalogue shot, so we stacked the shoes. A tower of pairs balancing on each other, soles pressed into uppers, turning slowly on a soft pastel gradient.",
      "To make that believable the shoes had to be real. Each pair was captured with photogrammetry, cleaned up and retopologised, then textured so the leather grain, the mesh and the stitching hold up in close-up. The process shots in the gallery show the stages: camera positions around the shoe, the raw point cloud, the sculpt.",
      "The lighting is deliberately gentle. Large soft sources, a hint of pink and blue from the backdrop, nothing dramatic, so the colourways of the shoes do the talking. The stack loosens, tumbles and resolves into The Athlete's Foot wordmark. We cut it for landscape, square and vertical so it could run everywhere the campaign did.",
    ],
    brief: 'Make sneaker product launches stop the scroll on social media.',
    tools: ['Cinema 4D', 'AfterEffects', 'Photoshop', 'Substance 3D'],
    images: [
      `${IMG}/Athletesfoot/taf_anim_v.webm`,
      `${IMG}/Athletesfoot/taf_image_01.webp`,
      `${IMG}/Athletesfoot/taf_image_02.webp`,
      `${IMG}/Athletesfoot/taf_image_03.webp`,
      `${IMG}/Athletesfoot/screenshot_01.webp`,
      `${IMG}/Athletesfoot/screenshot_02.webp`,
      `${IMG}/Athletesfoot/screenshot_03.webp`,
      `${IMG}/Athletesfoot/screenshot_04.webp`,
      `${IMG}/Athletesfoot/taf_vertical.webm`,
      `${IMG}/Athletesfoot/taf_landscape.webm`,
      `${IMG}/Athletesfoot/puma.webp`,
    ],
    layout: [
      { cols: 1, imgs: [9] },
      { cols: 1, imgs: [0] },
      { cols: 3, imgs: [1, 2, 3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 2, imgs: [6, 7] },
      { cols: 1, imgs: [8] },
    ]
  },
  grounded2020: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded: Truth',
    year: 2020,
    client: 'Pritličje',
    link: 'https://www.grounded.si',
    desc: [
      "Solidarity, elimination of inequality and peaceful co-existence assume the existence of truth, and truthfulness as the value of public action. In the post-truth world, these assumptions no longer exist.",
      "Those in positions of power often lie without legal or other social sanction. The ruling party-owned media spreads lies about those who resist them. Social networks increase the reach of conspiracy theories, while platforms are placed in the role of arbiters of truth.",
      "We turned that into a set of still lifes about how information is made, carried and silenced. An old television leaking something green and synthetic. A microphone wrapped in chain. A police baton lying among opened hard drives. Letter dice spelling the word on a crowd barrier. Each object is ordinary; the staging is what makes it uneasy.",
      "The look is forensic: near-black backgrounds, hard directional light, and two signal colours, an acid green and an alarm red, used the way a terminal uses them. Type is set like evidence labels, small, monospaced and precise, with the artist and speaker lists stacked in colour over the renders. The same objects carry the poster, the banners and the vertical formats.",
    ],
    brief: 'Build an identity around truth and resistance in a post-truth era.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2020/Grounded_poster_2.webp`,
      `${IMG}/Grounded_2020/Artboard-26.webp`,
      `${IMG}/Grounded_2020/Artboard-26-copy-2.webp`,
      `${IMG}/Grounded_2020/grounded_resnica.webp`,
      `${IMG}/Grounded_2020/Grounded2020_anim_v.webm`,
      `${IMG}/Grounded_2020/Grounded2020_2_anim_v.webm`,
      `${IMG}/Grounded_2020/grounded2020_ekran.webm`,
      `${IMG}/Grounded_2020/grounded2020_fence.webm`,
      `${IMG}/Grounded_2020/grounded2020_mikrofon.webm`,
    ],
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 1, imgs: [6] },
      { cols: 2, imgs: [7, 8] },
    ]
  },
  grounded2018: {
    color: 'blue',
    category: ['Print', 'Branding'],
    name: 'Festival Grounded 2018',
    year: 2018,
    client: 'Pritličje',
    desc: [
      "The second edition of Grounded asked about intimacy in the age of artificial intelligence. We answered with one gesture: a mechanical hand holding something soft. A brain, an eye, a block of bright silicone. The hand is jointed brass and carbon fibre, the thing it holds is glossy and vulnerable, and the whole tension of the theme is in how carefully it is being held.",
      "We kept the colour flat and confident, cyan, magenta and violet backdrops with no gradients to hide behind, so the objects read instantly at poster size and from across a street. The materials do the storytelling: polished metal against rubbery pink, a hard machine being gentle.",
      "Typography is a monospaced face for the title, a nod to the machine doing the talking, paired with a friendly rounded sans for dates and the festival mark. The system ran across the poster, a series of square variations for each object, and the printed tickets.",
    ],
    brief: 'Translate the tension of digital intimacy into a festival identity.',
    tools: ['Cinema 4D', 'Photoshop', 'Illustrator'],
    images: [
      `${IMG}/Grounded_2018/plakat.webp`,
      `${IMG}/Grounded_2018/grounded_2018_anim_v.webm`,
      `${IMG}/Grounded_2018/44396997_2300717590163245_3256152537651807309_n.webp`,
      `${IMG}/Grounded_2018/Grounded_2018_instagram.webm`,
      `${IMG}/Grounded_2018/Grounded_2018_music.webm`,
      `${IMG}/Grounded_2018/Grounded_2018_03.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
    ]
  },
  tamtam: {
    color: 'blue',
    category: ['Print'],
    name: 'Mesta pešcem — TamTam',
    year: 2018,
    award: 'Mestni plakat leta — TamTam 2018',
    desc: [
      "A poster for pesec.si with one job: make the case for cities that belong to people on foot. We wanted a single image you understand from the other side of the street, before you have read a word.",
      "So the city stands on a shoe. A worn canvas high-top is tipped on its heel, and a whole skyline, towers, blocks and a strip of green, grows out of the sole. The scuffed toe cap matters as much as the buildings; it says this shoe has done the walking. Everything floats on a calm sky blue with a soft shadow, and the line Mesta pešcem! sits small at the bottom, because the picture has already said it.",
      "The poster won City Poster of the Year at TamTam 2018 and ran on street displays across Ljubljana.",
    ],
    brief: 'Design a city poster that sparks conversation about pedestrian rights.',
    tools: ['Photoshop', 'Illustrator'],
    images: [
      `${IMG}/TamTam_Hoja--moj-transport_plakat-tisk.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
    ]
  },
  ment: {
    color: 'purple',
    category: ['Motion', '3D'],
    name: 'AppointMENT 4.0',
    year: 2019,
    desc: [
      "The visual for AppointMENT 4.0 started from a feeling more than a brief: being the one lit thing in a dark room. We built a figure standing in a forest at night, wearing a puffer jacket that glows from the inside, the only light source in the frame.",
      "Then we broke it. The arms run long, past the knees, down to the ground, and end in red hands resting on the forest floor. It is a small wrong detail that turns a fashion image into something stranger, and it gave the event a character people remembered.",
      "The palette is nearly monochrome, deep violet trunks and black, so the white of the jacket and the red of the arms carry everything. Lighting is practical: what the jacket throws on the trees is all there is.",
    ],
    brief: 'Build a visual identity for a music and arts event from scratch.',
    tools: ['Cinema 4D', 'Photoshop', 'Illustrator'],
    images: [
      `${IMG}/AppointMENT_4.0/AppointMENT_poster.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
    ]
  },
  halloween: {
    color: 'purple',
    category: ['Photogrammetry', '3D', 'Motion'],
    name: "Halloween — The Athlete's Foot",
    year: 2021,
    client: "The Athlete's Foot",
    desc: [
      "Halloween campaigns tend to reach for cobwebs. We went for a haunted candy shop instead: a velvet throne in an ultraviolet jungle with a pumpkin glowing in the leaves, a pit of striped sweets with a sneaker sunk into it, a cave lined with blue fur that opens around the shoe like something breathing. Sweet at first glance, a little off at the second.",
      "The technical backbone of this project was photogrammetry. Every sneaker was hand-scanned using a DSLR rig, roughly 200–300 photos per shoe, shot from every conceivable angle under controlled lighting. Those images were then processed into raw point clouds, millions of vertices that captured every stitch, crease, and texture detail of the physical product.",
      "From there, the real work began. Each point cloud was imported into ZBrush for cleanup: removing noise, filling gaps, rebuilding topology into something render-ready. The poly counts were enormous. A single shoe could easily hit 8–10 million polygons before decimation, and the full scenes pushed workstations to their absolute limits.",
      "Having true-to-life scans is what let us be reckless with everything around them. The shoes stay photographic while the worlds go saturated and synthetic, lit in magenta, violet and electric blue. That contrast, a real product in an unreal place, is the whole look of the campaign.",
    ],
    brief: 'Turn a seasonal retail campaign into something cinematic and shareable.',
    tools: ['Cinema 4D', 'ZBrush', 'Redshift', 'AfterEffects', 'Substance 3D'],
    images: [
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_01.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_02.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_03.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_04.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_05.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_06.webp`,
      `${IMG}/Athletesfoot_halloween/Athletesfoot_halloween_07.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_1.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_2.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_3.webp`,
      `${IMG}/Athletesfoot_halloween/screenshot_zbrush.webp`,
      `${IMG}/Athletesfoot_halloween/halloween_banner.webm`,
      `${IMG}/Athletesfoot_halloween/halloween_story.webm`,
      `${IMG}/Athletesfoot_halloween/adidas_zx_lowpoly.webp`,
      `${IMG}/Athletesfoot_halloween/DSC_0213.webp`,
      `${IMG}/Athletesfoot_halloween/DSC_9820.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 3, imgs: [1, 2, 3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 2, imgs: [6, 10] },
      { cols: 3, imgs: [7, 8, 9] },
    ]
  },
  blackfriday: {
    color: 'gray',
    category: ['Motion', '3D'],
    name: "Black Friday — The Athlete's Foot",
    year: 2021,
    client: "The Athlete's Foot",
    desc: [
      "Black Friday is the loudest week in retail, so we took the colour out. The whole film is white shoes in a white room, and one black material.",
      "The black is a liquid. It pours over a clean white sneaker, drips off the sole and pools on a sheet of glass, then fills a clear display case until the shoe is sitting in it. We spent most of the time on how it moves: thick and glossy, slow enough to read, with highlights that keep its shape visible against grey. The title is cast from the same stuff and sealed under clear film like a product label.",
      "A wall of tumbling white trainers gives the cut its one busy moment, then it settles back to a single object. Everything ends on the red wing of The Athlete's Foot, the only colour in the piece.",
    ],
    brief: 'Maximum visual impact for a crowded Black Friday retail moment.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Substance 3D'],
    images: [
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_anim_01.webp`,
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_anim_02.webp`,
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_01.webp`,
      `${IMG}/Athletesfoot_blackfriday/Athletesfoot_blackfriday_02.webp`,
      `${IMG}/Athletesfoot_blackfriday/bftaf.webm`,
    ],
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 3] },
    ]
  },
  largavida: {
    color: 'orange',
    category: ['Print', 'Branding'],
    name: 'LargaVida Limited Edition',
    year: 2022,
    desc: [
      "LargaVida is an XO rum with the sea on its label: a sunset, a dolphin, hand-drawn lettering. For the limited edition the bottle needed a finishing piece, something you would keep after the rum was gone. We designed the stopper as a small sculpture, a speedboat cutting across a disc of waves.",
      "The work was mostly form. The boat had to read as a boat at the size of a thumb, so the hull lines are simplified and the wake is exaggerated into a few bold ridges. We sculpted it, then rebuilt the surface into clean, even geometry so it could be produced without losing the edges, and the gallery shows that step: the wireframe, the remesh, the flow of the surface.",
      "It is finished in gold to sit with the collar of the bottle, and lit in the final image the way spirits are photographed: a soft key, a bright rim, the amber doing the rest.",
    ],
    brief: 'Design premium packaging and digital presence for a limited release.',
    tools: ['Photoshop', 'Illustrator'],
    images: [
      `${IMG}/LargaVida/01_larga_vida_desktop.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_01.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_02.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_03.webp`,
      `${IMG}/LargaVida/larga_vida_screenshot_04.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
    ]
  },
  newedge: {
    color: 'white',
    category: ['Print'],
    name: 'NewEdge Magazine',
    year: 2020,
    desc: [
      "For issue XI of NewEdge we built the cover and its opening images as sets rather than illustrations. Small staged rooms, each one a little too perfect: a bathtub on a checkerboard floor in front of orange tile, a staircase leading to a figure taking a selfie against a blue circle, green velvet curtains, gold taps, a rubber duck.",
      "The mood is a shop window. Saturated colour blocking, orange against green against sky blue, glossy materials, plants placed like props. The figures are mannequins on purpose; the scenes are about performing a life for a camera, and the phone is in every one of them.",
      "The masthead is part of the set. NewEdge is spelled in inflated gold balloon letters and matte black bars, standing in the scene and lit by the same lights, so the type and the image are one object. On the printed cover it sits tight to the spine with the issue number set small above.",
    ],
    brief: 'Create an editorial design system bridging digital culture and print.',
    tools: ['InDesign', 'Photoshop', 'Illustrator'],
    images: [
      `${IMG}/NewEdge_magazine/NewEdge_magazine_01.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_magazine_02.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_magazine_03.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_magazine_04.webp`,
      `${IMG}/NewEdge_magazine/NewEdge_reality_01.webm`,
      `${IMG}/NewEdge_magazine/NewEdge_reality_02.webm`,
    ],
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 3] },
      { cols: 2, imgs: [4, 5] },
    ]
  },
  grounded2023: {
    color: 'blue',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2023',
    year: 2023,
    client: 'Pritličje',
    desc: [
      "The 2023 identity is built on a contradiction: the language of jewellery used to talk about violence. The hero object is an ornate chrome egg, set with blue stones and wrapped in fine filigree, the kind of thing made to be kept behind glass. Next to it, a heap of brass cartridges.",
      "We modelled everything as if for a jeweller's catalogue. Polished metal on a soft lavender gradient, a peace sign worked into a pendant with hanging globes, the word PEACE bent into a chrome emblem around the festival name. The reflections are the hard part of a scene like this, so the lighting is a few large, clean shapes that describe the form without clutter.",
      "A sharp lime green is the one loud colour, used for frames and for the torn shapes that reveal the egg in the animated formats. Type is a high-contrast serif for dates, small and confident, and it leaves the object alone.",
    ],
    brief: 'Visual identity and 3D animation for the 2023 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/Grounded_2023/Grounded_2023_01.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_02.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_03.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_04.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_05.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_06.webm`,
      `${IMG}/Grounded_2023/Grounded_2023_07.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 1, imgs: [3] },
      { cols: 2, imgs: [4, 5] },
      { cols: 1, imgs: [6] },
    ]
  },
  grounded2026: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2026',
    year: 2026,
    client: 'Pritličje',
    desc: [
      "Grounded turned ten, and we marked it with toys. A water pistol built like a real weapon, feeding out a till receipt. A pocket pet whose little screen shows a mushroom cloud. A cash register with MONEYYY on its display and a drawer full of gold. Everything is moulded in translucent neon plastic, the kind you can see the batteries through.",
      "The idea is in the material. Injection-moulded green, hot pink and blue, with visible screws, seams and circuit boards inside, lit hard against black so the plastic glows at its edges. It looks harmless and collectible, which is exactly why the subjects sit so uncomfortably in it.",
      "The system is a kit of parts: a red cog-shaped label carrying the festival text, a pressed metal token for the mark, and a big serif 10 embossed into the shells. We designed it so each object could carry a poster on its own, and so the animations could simply turn the object over in the hand.",
    ],
    brief: 'Visual identity and motion design for the 2026 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/Grounded_2026/Render_still_01_CC.webp`,   // hero — wide landscape render
      `${IMG}/Grounded_2026/Grounded_2026_web.webm`,    // 16:9 web film: first, full-width gallery row
      `${IMG}/Grounded_2026/Grounded_2026_anim.webm`,
      `${IMG}/Grounded_2026/Render_closeup_CC.webp`,
      `${IMG}/Grounded_2026/Render_still_02_CC.webp`,
      `${IMG}/Grounded_2026/img.webp`,
      `${IMG}/Grounded_2026/img-1.webp`,
      `${IMG}/Grounded_2026/img-2.webp`,
      `${IMG}/Grounded_2026/img-3.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 1, imgs: [7] },
    ]
  },
  grounded2025: {
    color: 'black',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2025',
    year: 2025,
    client: 'Pritličje',
    desc: [
      "This edition went close. The visuals are macro studies of something growing on dark rock: soft, folded forms in pink and deep red, somewhere between coral, fungus and tissue. We wanted an image that feels alive before it means anything.",
      "The surfaces were the design problem. Light passes into the forms and comes back out warm, so the folds glow from within, while the rock stays matte and cold. A shallow depth of field keeps only a slice in focus, the way a real macro lens would, and the camera barely moves.",
      "The motion pieces are slow on purpose. They breathe rather than animate, and they work as backdrops on stage as much as posts in a feed.",
    ],
    brief: 'Visual identity and motion design for the 2025 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/Grounded 2025/gr2025cover.webp`,
      `${IMG}/Grounded 2025/Grounded_2025_web.webm`,
      `${IMG}/Grounded 2025/IG_story_01.webm`,
      `${IMG}/Grounded 2025/IG_story_02.webm`,
      `${IMG}/Grounded 2025/IG_story_03.webm`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 1, imgs: [1] },
      { cols: 3, imgs: [2, 3, 4] },
    ]
  },
  grounded2024: {
    color: 'blue',
    category: ['Motion', '3D'],
    name: 'Festival Grounded 2024',
    year: 2024,
    client: 'Pritličje',
    desc: [
      "The 2024 key visual happens underwater. A skull drifts in deep blue, caught in fishing nets, and a translucent tentacle rises through it and wraps around it, dotted with suckers and trailing bubbles.",
      "We built it as a sequence rather than a single poster. Across the series the tentacle climbs, coils and tightens, so the posters read like frames from one slow movement, and the animated versions simply play it. The skull picks up algae along the way.",
      "The palette is two colours: the blue of deep water and a milky pink for the creature, with light scattering inside it so it looks soft and wet, not solid. Fine particles and bubbles give the water its depth. Typography stays small in a corner; the image is tall, quiet and a little menacing, and it did not need help.",
    ],
    brief: 'Visual identity and motion design for the 2024 festival edition.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects', 'Photoshop'],
    images: [
      `${IMG}/Grounded_2024/Grounded_2024_01.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_02.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_03.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_04.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_05.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_06.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_07.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_sticker_01.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_sticker_02.webp`,
      `${IMG}/Grounded_2024/Grounded_2024_comp.webm`,
      `${IMG}/Grounded_2024/Grounded_2024_story.webm`,
      `${IMG}/Grounded_2024/Grounded_2024_mehurcki.webm`,
    ],
    layout: [
      { cols: 1, imgs: [9] },
      { cols: 2, imgs: [0, 1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 1, imgs: [10] },
      { cols: 2, imgs: [5, 6] },
      { cols: 2, imgs: [7, 8] },
      { cols: 1, imgs: [11] },
    ]
  },
  radenci: {
    color: 'orange',
    category: ['Motion'],
    name: 'Radenci — Prostorska Projekcija',
    year: 2026,
    desc: [
      "A spatial projection for children in Radenci: a room where the walls become the story. The audience stands inside it and follows a small gnome in a red hat on a journey that starts in the forest, drops underground and ends under water.",
      "We designed it as a film that has no single screen. The scenes had to hold up across corners and uneven surfaces, so compositions are built around one clear point of attention, usually the gnome and a light he is following, with the rest of the frame kept dark enough to melt into the room. A lantern in the undergrowth, a glowing orb in a cave, a giant eye opening in the rock.",
      "The look is closer to stop-motion than to a cartoon. Textures are tactile, moss, wet stone, felt, and the lighting is warm and practical, which makes the world feel like a set you could touch. For a young audience that matters: the scary moments, the cave, the warning signs, the big fish, stay gentle.",
      "The photos from the room are the real result. Children reaching for the orb on the wall is the interaction we were designing for.",
    ],
    brief: 'Transform architectural surfaces into a living projection experience.',
    tools: ['Cinema 4D', 'AfterEffects'],
    images: Array.from({ length: 31 }, (_, i) => {
      const names = [
        'P1_S1_K01_0323.webp','P1_S1_K02_0533.webp','P1_S1_K02_i1_0460.webp',
        'P1_S2_K04_0110.webp','P1_S2_K05_0238.webp','P1_S3_K03_0282.webp',
        'P1_S3_K05_0054.webp','P1_S3_K06_0150.webp','P1_S3_K06_0329.webp',
        'P1_S3_K07_0377.webp','P1_S3_K07_0406.webp','P2_S02_K03_0118.webp',
        'P2_S02_K03_0529.webp','P2_S1_K01_0227.webp','P2_S1_K01_A&B_0046.webp',
        'P2_S1_K02_0806.webp','P2_S1_K03_0182.webp','P2_S1_K03_B_i1_0397.webp',
        'P2_S2_K01_0376.webp','P2_S2_K01_0701.webp','P2_S2_K01_0841.webp',
        'P2_S3_K03_0482.webp','P2_S3_K03_B_02_0605.webp','P2_S3_K05_0026.webp',
        'P2_S3_K05_0477.webp',
        'IMG_4065.webp','IMG_4069.webp','IMG_4073.webp',
        'IMG_4075.webp','IMG_4100.webp','IMG_4101.webp'
      ];
      return `${IMG}/Radenci_prostorska_projekcija/${names[i]}`;
    }),
    layout: [
      { cols: 2, imgs: [0, 1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 3, imgs: [7, 8, 9] },
      { cols: 2, imgs: [10, 11] },
      { cols: 3, imgs: [12, 13, 14] },
      { cols: 2, imgs: [15, 16] },
      { cols: 3, imgs: [17, 18, 19] },
      { cols: 2, imgs: [20, 21] },
      { cols: 3, imgs: [22, 23, 24] },
      { cols: 3, imgs: [25, 26, 27] },
      { cols: 3, imgs: [28, 29, 30] },
    ]
  },
  lab: {
    color: 'gray',
    category: ['Lab'],
    name: 'Lab — Experiments',
    desc: ['Personal experiments, 3D explorations, and creative coding projects.'],
    tools: ['Cinema 4D', 'Houdini', 'Redshift'],
    images: [
      `${IMG}/Lab/Fly_fico.webm`,
      `${IMG}/Lab/Furry_jezik.webm`,
      `${IMG}/Lab/gold.webm`,
      `${IMG}/Lab/Particles2.webm`,
      `${IMG}/Lab/lab_comp.webm`,
      `${IMG}/Lab/lab_impol.webm`,
      `${IMG}/Lab/lab_sandunes.webm`,
      `${IMG}/Lab/Dream_01.webp`,
      `${IMG}/Lab/Dream_02.webp`,
      `${IMG}/Lab/Dream_03.webp`,
      `${IMG}/Lab/Dream_03-2.webp`,
      `${IMG}/Lab/Dream_04-2.webp`,
      `${IMG}/Lab/lab_kristal.webm`,
      `${IMG}/Lab/lab_kristal_story.webm`,
      `${IMG}/Lab/kristal0020.webp`,
      `${IMG}/Lab/kristal0025.webp`,
      `${IMG}/Lab/kristal0026.webp`,
      `${IMG}/Lab/qurtz0012.webp`,
      `${IMG}/Lab/qurtz0033.webp`,
      `${IMG}/Lab/testgoba_3.webp`,
      `${IMG}/Lab/take_3_0138.webp`,
      `${IMG}/Lab/Kersnikova_logo_take4_4.webp`,
      `${IMG}/Lab/end.webp`,
      `${IMG}/Lab/lm62ZTf.webp`,
      `${IMG}/Lab/lab_flag.webm`,
      `${IMG}/Lab/mecha.webp`,
      `${IMG}/Lab/mecha_02.webp`,
      `${IMG}/Lab/mecha_03.webp`,
      `${IMG}/Lab/mecha_04.webp`,
      `${IMG}/Lab/mecha_grid_8.webp`,
      `${IMG}/Lab/mecha_grid_9.webp`,
      `${IMG}/Lab/mecha_grid_11.webp`,
      `${IMG}/Lab/LaLuna_test_RUN.webm`,
      `${IMG}/Lab/ENKI-screensaver_1.webm`,
      `${IMG}/Lab/kersnikova_logo_preview.webm`,
      `${IMG}/Lab/scandianvian.[0000-0244].webm`,
      `${IMG}/Lab/Short_napis 16-9_2.webm`,
      `${IMG}/Lab/222.webp`,
      `${IMG}/Lab/hand.webp`,
      `${IMG}/Lab/legs.webp`,
      `${IMG}/Lab/face.webp`,
      `${IMG}/Lab/zadni_2.webp`,
      `${IMG}/Lab/puma.webp`,
      `${IMG}/Lab/Bossplast_smoke.webp`,
      `${IMG}/Lab/BF.webp`,
      `${IMG}/Lab/Bossplast.webp`,
      `${IMG}/Lab/2880x1560.webp`,
      `${IMG}/Lab/car.webm`,
    ],
    layout: [
      { cols: 1, imgs: [47] },
      { cols: 2, imgs: [0, 1] },
      { cols: 2, imgs: [2, 4] },
      { cols: 1, imgs: [5] },
      { cols: 2, imgs: [3, 6] },
      { cols: 3, imgs: [7, 8, 9] },
      { cols: 2, imgs: [10, 11] },
      { cols: 1, imgs: [12] },
      { cols: 2, imgs: [13, 14] },
      { cols: 3, imgs: [15, 16, 17] },
      { cols: 2, imgs: [18, 19] },
      { cols: 1, imgs: [20] },
      { cols: 2, imgs: [21, 22] },
      { cols: 2, imgs: [23, 24] },
      { cols: 1, imgs: [25] },
      { cols: 2, imgs: [26, 27] },
      { cols: 3, imgs: [28, 29, 30] },
      { cols: 2, imgs: [31, 32] },
      { cols: 1, imgs: [33] },
    ]
  },
  kersnikova: {
    color: 'pink',
    category: ['Print', 'Branding'],
    name: 'Kersnikova',
    year: 2021,
    desc: [
      "Kersnikova is an institution where art meets science and the lab is part of the gallery. For the HAIP live programme we made the poster out of its tools: a white moulded shell, a funnel, connectors and clamps, tied together by one long red tube that loops around everything like a drawing.",
      "It is a two-colour job by design. White objects on white paper, with red for the tube, the type and the times, so the print is cheap to produce and impossible to miss. The object is shot soft and shadowless, which makes it feel clinical; the red line gives it a pulse.",
      "The grid is simple and repeatable: title and date top left, the programme set in two time blocks, the institution's name turned up the right edge. The same parts carry over to the folded programme, where the red line continues across the spread, and the poster held its own pasted on a wall full of graffiti.",
    ],
    brief: 'Translate an experimental institution\'s spirit into accessible design.',
    tools: ['Photoshop', 'Illustrator', 'InDesign'],
    images: [
      `${IMG}/Kersnikova/Plakat-500x700-B2.webp`,
      `${IMG}/Kersnikova/slika nova.webp`,
      `${IMG}/Kersnikova/zlozenka2.webp`,
      `${IMG}/Kersnikova/zvocnik_finished.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 1, imgs: [3] },
    ]
  },
  natureta_renders: {
    color: 'yellow',
    category: ['3D'],
    name: 'Natureta Product Renders',
    year: 2023,
    desc: [
      "A library of product renders for Natureta, built so the brand never has to book a studio for a new jar. Every product exists as a 3D model: the glass, the lid, the label, and what is inside.",
      "What is inside was the challenge. A pepper spread has to look thick and flecked, pickles have to sit in clear brine, and the glass has to bend all of it the way a real jar does. We spent the time on those materials and on a lighting setup that behaves like a product photographer's: a big soft key, a bright edge on the lid, a clean falloff on the backdrop.",
      "From one setup we produced single packshots on white, grouped line-ups on brand green, a styled scene on slate with garlic and herbs, and loose, floating compositions for social. Because it is all the same light and the same camera logic, anything rendered later sits next to the first images without a seam.",
    ],
    brief: 'Create photorealistic product renders that rival studio photography.',
    tools: ['Cinema 4D', 'Redshift', 'Photoshop'],
    images: [
      `${IMG}/Natureta product renders/izdelki.webp`,
      `${IMG}/Natureta product renders/Mockup_2.webp`,
      `${IMG}/Natureta product renders/float_2.webp`,
      `${IMG}/Natureta product renders/kumarica.webp`,
      `${IMG}/Natureta product renders/vsi_2.webp`,
      `${IMG}/Natureta product renders/ETA_animacija_FINAL_2_2.webp`,
      `${IMG}/Natureta product renders/Kozarec_eta0001.webp`,
      `${IMG}/Natureta product renders/Kozarec_eta0013.webp`,
      `${IMG}/Natureta product renders/Kozarec_eta0015.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
      { cols: 2, imgs: [3, 4] },
      { cols: 1, imgs: [5] },
      { cols: 3, imgs: [6, 7, 8] },
    ]
  },
  natureta: {
    color: 'orange',
    category: ['3D', 'Branding'],
    name: 'Natureta 100 Let',
    year: 2023,
    desc: [
      "Natureta turned one hundred. The campaign line is Stoletje ustvarjanja slastne hrane, a century of making delicious food, signed off with Hvala, narava: thank you, nature.",
      "We took the thank-you literally and composed each poster as a bouquet. The jar stands in the middle and the arrangement around it is made of produce and flowers, a romanesco, kale, a head of garlic, ginger flowers and a bird of paradise, set against a calm grey or a deep violet. It is a still life, formal and a little celebratory, and the jar is the guest of honour.",
      "The layout is built for the street. White type top left, the logo locked to the corner, the anniversary mark bottom right, and plenty of quiet space so it reads from a passing car. It ran on city-light displays.",
    ],
    brief: 'Celebrate 100 years of heritage while feeling fresh and modern.',
    tools: ['Photoshop', 'Cinema 4D'],
    images: [
      `${IMG}/Natureta/Prebranec-Natureta-657f495f8b596.webp`,
      `${IMG}/Natureta/Prebranec-1-65708119051a5.webp`,
      `${IMG}/Natureta/Prebranec-2-657081193738f.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [1, 2] },
    ]
  },
  accbox: {
    color: 'blue',
    category: ['Motion', '3D'],
    name: 'AccountingBox',
    year: 2024,
    client: 'AccountingBox',
    desc: [
      "AccountingBox needed to explain software features without showing screens that would be out of date in a year. We gave the product a body instead: a blue cube. Everything the software does is something the cube does.",
      "It sorts a grid of scattered shapes into order. It pulls a storm of loose paper into itself. It grows out of a pot, block by block, like a plant. It sits on the sofa as a cushion and on the wall as a picture. Each animation is one idea, a few seconds long, and loops cleanly.",
      "The system is strict so the loops feel like one family: a periwinkle world, the brand blue for the cube, and small accents of coral, green and yellow. Soft, even light, rounded furniture, and the same easing on every move. We built a handful of room sets, a living room, a home office, a larger office, so the cube always turns up somewhere familiar.",
    ],
    brief: 'Explain accounting software features through a consistent motion system.',
    tools: ['Cinema 4D', 'Redshift', 'AfterEffects'],
    images: [
      `${IMG}/AccountingBox/4_loop.webm`,
      `${IMG}/AccountingBox/intro.webm`,
      `${IMG}/AccountingBox/freetrial.webm`,
      `${IMG}/AccountingBox/hiter.webm`,
      `${IMG}/AccountingBox/kjerkoli.webm`,
      `${IMG}/AccountingBox/kjerkoli_prvomesto.webm`,
      `${IMG}/AccountingBox/kjerkoli_drugomesto.webm`,
      `${IMG}/AccountingBox/podpora.webm`,
      `${IMG}/AccountingBox/1_loop.webm`,
      `${IMG}/AccountingBox/2_intro.webm`,
      `${IMG}/AccountingBox/6_intro.webm`,
      `${IMG}/AccountingBox/racunovodje_cover_final.webp`,
      `${IMG}/AccountingBox/Podjetja_cover.webp`,
    ],
    layout: [
      { cols: 1, imgs: [0] },
      { cols: 2, imgs: [11, 12] },
      { cols: 1, imgs: [1] },
      { cols: 3, imgs: [2, 3, 4] },
      { cols: 2, imgs: [5, 6] },
      { cols: 1, imgs: [7] },
      { cols: 3, imgs: [8, 9, 10] },
    ]
  },
};

const COLOR_HEX = {
  red: '#e74c3c', orange: '#e67e22', yellow: '#f1c40f', green: '#2ecc71',
  cyan: '#00bcd4', blue: '#3498db', purple: '#9b59b6', pink: '#e91e8a',
  black: '#222222', white: '#e0e0e0', gray: '#888888',
};

// Build flat list of grid items: one per image, tagged with project/year
// Color gets filled in async after image loads
const gridItems = [];
const gridExclude = /screenshot|zbrush|Mockup|larga_vida_screenshot/i;
for (const [projId, proj] of Object.entries(projects)) {
  for (const src of proj.images) {
    if (gridExclude.test(src)) continue;
    gridItems.push({
      src,
      project: projId,
      projectName: proj.name,
      year: proj.year,
      color: proj.color || 'gray',
      category: proj.category || [],
    });
  }
}

function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
shuffle(gridItems);

// Expose shared data to other scripts (script.js, overlay.js, lab.js, tools/build-pages.js)
window.IMG = IMG;
window.projects = projects;
window.COLOR_HEX = COLOR_HEX;
window.gridItems = gridItems;
window.gridExclude = gridExclude;
})();
