/* ===================================================================
   tools/build-pages.js — writes the static project pages and the sitemap.

     node tools/build-pages.js

   Run it after changing projects.js (adding a project, editing text or
   images) and commit the result. The site itself has no build step; this
   only regenerates files that are derived from the project data:

     work/<id>.html   one page per project: the same view the site opens
                      in place, already in the HTML, with its own title,
                      description, share image and structured data
     sitemap.xml      the four main pages, every project page and every
                      Lab app page
     apps/<id>/       the site of an app that has one, by way of
                      tools/build-app-site.js

   The project markup comes from project-template.js, the same function
   the browser uses, so the static pages cannot drift from the live view.
   =================================================================== */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ORIGIN = 'https://lukagrcar.com/';
const read = file => fs.readFileSync(path.join(ROOT, file), 'utf8');

global.window = {};
require(path.join(ROOT, 'projects.js'));
const projects = global.window.projects;
const Template = require(path.join(ROOT, 'project-template.js'));

// Reuse whatever cache-busting versions the Work page currently links, so a
// version bump there only needs this script re-run.
const gridHtml = read('grid.html');
const versioned = (file) => {
  const m = gridHtml.match(new RegExp(file.replace('.', '\\.') + '(\\?v=\\d+)?'));
  return m ? m[0] : file;
};

const esc = text => String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const clamp = (text, max) => (text.length > max ? text.slice(0, max - 1).trim() + '…' : text);
const absolute = file => ORIGIN + encodeURI(file);

function pageFor(id) {
  const p = projects[id];
  const kind = (p.category || []).join(' & ') || 'Project';
  const title = `${p.name} — ${kind} by Luka Grčar`;
  const description = clamp([p.brief, (p.desc || [])[0]].filter(Boolean).join(' '), 160);
  const url = `${ORIGIN}work/${id}`;
  const image = absolute(Template.posterOf(p.images[0]));
  const view = Template.html(projects, id, { linkFor: other => `work/${other}.html`, prerender: true });

  const structured = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CreativeWork',
        '@id': url,
        name: p.name,
        url,
        description: [p.brief].concat(p.desc || []).filter(Boolean).join(' '),
        image,
        dateCreated: p.year ? String(p.year) : undefined,
        genre: p.category,
        creator: { '@type': 'Person', '@id': ORIGIN + '#person', name: 'Luka Grčar', url: ORIGIN },
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Luka Grčar', item: ORIGIN },
          { '@type': 'ListItem', position: 2, name: 'Work', item: ORIGIN + 'grid.html' },
          { '@type': 'ListItem', position: 3, name: p.name, item: url },
        ],
      },
    ],
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <!-- Generated by tools/build-pages.js from projects.js. Do not edit by hand. -->
  <base href="../" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <title>${esc(title)}</title>
  <meta name="robots" content="noai, noimageai" />
  <link rel="icon" type="image/png" href="favicon.png" />
  <meta name="description" content="${esc(description)}" />
  <link rel="canonical" href="${url}" />
  <meta property="og:title" content="${esc(title)}" />
  <meta property="og:description" content="${esc(description)}" />
  <meta property="og:image" content="${image}" />
  <meta property="og:url" content="${url}" />
  <meta property="og:type" content="article" />
  <meta name="twitter:card" content="summary_large_image" />
  <link rel="stylesheet" href="${versioned('tokens.css')}" />
  <link rel="stylesheet" href="${versioned('overlay.css')}" />
  <style>
    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }
    html { scrollbar-gutter: stable; }
  </style>
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-RXZ65KVMCQ"></script>
  <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-RXZ65KVMCQ');</script>
  <script type="application/ld+json">
${JSON.stringify(structured, null, 2)}
  </script>
</head>
<body class="page-project project-page project-open">

  <button class="overlay-close visible" id="overlayClose" aria-label="Close and go to all work"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="1" y1="1" x2="17" y2="17"/><line x1="17" y1="1" x2="1" y2="17"/></svg></button>
  <div class="overlay open" id="overlay" role="region" aria-label="${esc(p.name)}">
    <div class="overlay-inner" id="overlayInner">${view.html}
    </div>
  </div>
  <noscript><p style="padding:24px"><a href="grid.html">All work</a> · <a href="index.html">Luka Grčar</a></p></noscript>

  <!-- overlay.js re-renders the view above and makes it interactive -->
  <script>window.PROJECT_PAGE = ${JSON.stringify(id)};</script>
  <script src="motion.js"></script>
  <script defer src="${versioned('projects.js')}"></script>
  <script defer src="${versioned('project-template.js')}"></script>
  <script defer src="${versioned('overlay.js')}"></script>
</body>
</html>
`;
}

// ---- project pages ----
const ids = Template.projectIds(projects);
fs.mkdirSync(path.join(ROOT, 'work'), { recursive: true });
const keep = new Set(ids.map(id => id + '.html'));
fs.readdirSync(path.join(ROOT, 'work')).forEach((file) => {
  if (file.endsWith('.html') && !keep.has(file)) fs.unlinkSync(path.join(ROOT, 'work', file));   // project removed
});
ids.forEach(id => fs.writeFileSync(path.join(ROOT, 'work', id + '.html'), pageFor(id)));

// ---- sitemap ----
// The Lab's app pages (apps/<id>.html) are written by hand, but they are
// listed here from apps.js so regenerating never drops them. An app with a
// site of its own (apps.js: site) has its pages written now and listed.
const AppSite = require('./build-app-site.js');
AppSite.build();
const apps = global.window.labApps || [];
const today = new Date().toISOString().slice(0, 10);
const xml = text => String(text).replace(/&/g, '&amp;').replace(/</g, '&lt;');
const imageTag = file => `    <image:image>\n      <image:loc>${xml(absolute(file))}</image:loc>\n    </image:image>\n`;
const urlTag = (loc, freq, priority, images) =>
  `  <url>\n    <loc>${ORIGIN}${loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${freq}</changefreq>\n    <priority>${priority}</priority>\n${images || ''}  </url>\n`;
const stills = p => p.images.map(Template.posterOf).filter((file, i, all) => all.indexOf(file) === i).slice(0, 12);

const sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n' +
  urlTag('', 'monthly', '1.0') +
  urlTag('grid.html', 'weekly', '0.9') +
  ids.map(id => urlTag('work/' + id, 'monthly', '0.8', stills(projects[id]).map(imageTag).join(''))).join('') +
  urlTag('lab.html', 'monthly', '0.7', projects.lab ? imageTag(Template.posterOf(projects.lab.images[0])) : '') +
  apps.map(app => (app.site
    ? AppSite.urlsFor(app).map((loc, i) => urlTag(loc, 'monthly', i ? '0.6' : '0.8', !i && app.cover ? imageTag(app.cover) : '')).join('')
    : urlTag('apps/' + app.id, 'monthly', '0.7', app.cover ? imageTag(app.cover) : ''))).join('') +
  urlTag('about.html', 'monthly', '0.8') +
  '</urlset>\n';
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap);

console.log(`Wrote ${ids.length} project pages to work/ and sitemap.xml`);
